/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) m130_mhe_cost_y_0_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {17, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {9, 1, 1};
static const casadi_int casadi_s4[3] = {47, 1, 1};
static const casadi_int casadi_s5[116] = 
  {34, 47, 0, 2, 4, 6, 10, 14,
  18, 19, 20, 21, 22, 26, 30, 32,
  33, 34, 35, 36, 37, 38, 39, 40,
  41, 42, 43, 44, 45, 46, 47, 48,
  49, 50, 51, 52, 53, 54, 55, 56,
  57, 58, 59, 60, 61, 62, 63, 64,
  65, 66, 20, 29, 21, 30, 22, 31,
  17, 23, 24, 26, 17, 23, 24, 26,
  17, 23, 24, 26, 26, 27, 28, 26,
  17, 18, 19, 32, 17, 18, 19, 33,
  17, 18, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 13,
  14, 15, 16, 17, 18, 19, 20, 21,
  22, 23, 24, 25, 26, 27, 28, 29,
  30, 31, 32, 33};
static const casadi_int casadi_s6[3] = {47, 0, 1};

/* m130_mhe_cost_y_0_fun_jac_ut_xt:(i0[17],i1[17],i2[0],i3[],i4[9])->(o0[47],o1[34x47,66nz],o2[47x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a000, a001, a002, a003, a004, a005, a006, a007, a008, a009, a010, a011;
  casadi_real a012, a013, a014, a015, a016, a017, a018, a019, a020, a021, a022, a023;
  casadi_real a024, a025, a026, a027, a028, a029, a030, a031, a032, a033, a034, a035;
  casadi_real a036, a037, a038, a039, a040, a041, a042, a043, a044, a045, a046, a047;
  casadi_real a048, a049, a050, a051, a052, a053, a054, a055, a056, a057, a058, a059;
  casadi_real a060, a061, a062, a063, a064, a065, a066, a067, a068, a069, a070, a071;
  casadi_real a072, a073, a074, a075, a076, a077, a078, a079, a080, a081, a082, a083;
  casadi_real a084, a085, a086, a087, a088, a089, a090, a091, a092, a093, a094, a095;
  casadi_real a096, a097, a098, a099, a100, a101, a102, a103, a104, a105, a106, a107;
  casadi_real a108, a109, a110, a111, a112, a113, a114, a115, a116, a117, a118, a119;
  casadi_real a120, a121, a122, a123, a124, a125, a126, a127, a128, a129, a130, a131;
  casadi_real a132, a133, a134;
  a000=arg[0]? arg[0][3] : 0;
  a001=arg[0]? arg[0][12] : 0;
  a002=(a000+a001);
  if (res[0]!=0) res[0][0]=a002;
  a002=arg[0]? arg[0][4] : 0;
  a003=arg[0]? arg[0][13] : 0;
  a004=(a002+a003);
  if (res[0]!=0) res[0][1]=a004;
  a004=arg[0]? arg[0][5] : 0;
  a005=arg[0]? arg[0][14] : 0;
  a006=(a004+a005);
  if (res[0]!=0) res[0][2]=a006;
  a006=arg[4]? arg[4][4] : 0;
  a007=1.3270000000000001e-02;
  a008=5.0000000000000000e-01;
  a009=1.2250000000000001e+00;
  a010=2.8814999999999998e+02;
  a011=6.4999999999999997e-03;
  a012=100.;
  a013=arg[0]? arg[0][9] : 0;
  a014=(a012*a013);
  a015=arg[4]? arg[4][8] : 0;
  a014=(a014+a015);
  a015=0.;
  a016=casadi_fmax(a014,a015);
  a016=(a011*a016);
  a016=(a010-a016);
  a017=2.1665000000000001e+02;
  a018=casadi_fmax(a016,a017);
  a010=(a018/a010);
  a019=4.2559323623598138e+00;
  a020=pow(a010,a019);
  a020=(a009*a020);
  a021=1.0000000000000000e-10;
  a022=casadi_fmax(a020,a021);
  a022=(a008*a022);
  a023=arg[0]? arg[0][0] : 0;
  a024=1.;
  a025=casadi_fmax(a023,a024);
  a026=(a022*a025);
  a027=(a026*a025);
  a027=(a007*a027);
  a028=6.4465099999999997e-01;
  a029=-6.6772809999999998e+00;
  a030=4.0187000000000000e+02;
  a018=(a030*a018);
  a018=sqrt(a018);
  a031=(a025/a018);
  a032=casadi_fmin(a031,a024);
  a033=1.0000000000000001e-01;
  a034=casadi_fmax(a032,a033);
  a035=casadi_fmin(a034,a024);
  a036=casadi_fmax(a035,a033);
  a037=(a029*a036);
  a028=(a028+a037);
  a037=5.6985242999999997e+01;
  a038=casadi_sq(a036);
  a039=(a037*a038);
  a028=(a028+a039);
  a039=-2.5248384700000000e+02;
  a040=(a038*a036);
  a041=(a039*a040);
  a028=(a028+a041);
  a041=6.1561736499999995e+02;
  a042=(a040*a036);
  a043=(a041*a042);
  a028=(a028+a043);
  a043=-8.3459076500000003e+02;
  a044=(a042*a036);
  a045=(a043*a044);
  a028=(a028+a045);
  a045=5.8734720100000004e+02;
  a046=(a044*a036);
  a047=(a045*a046);
  a028=(a028+a047);
  a047=-1.6562689000000000e+02;
  a048=(a046*a036);
  a048=(a047*a048);
  a028=(a028+a048);
  a048=5.6522999999999997e-02;
  a049=-9.9855799999999995e-01;
  a050=(a049*a036);
  a048=(a048+a050);
  a050=2.3926500000000002e+00;
  a051=(a050*a038);
  a048=(a048+a051);
  a051=-1.7378279999999999e+00;
  a052=(a051*a040);
  a048=(a048+a052);
  a052=arg[0]? arg[0][6] : 0;
  a053=casadi_sq(a052);
  a054=arg[0]? arg[0][7] : 0;
  a055=casadi_sq(a054);
  a056=(a053+a055);
  a057=(a048*a056);
  a028=(a028+a057);
  a057=-3.0486789999999999e+00;
  a058=5.4473490000000000e+00;
  a059=(a058*a036);
  a057=(a057+a059);
  a059=-9.6709250000000004e+00;
  a060=(a059*a038);
  a057=(a057+a060);
  a060=4.8268709999999997e+00;
  a061=(a060*a040);
  a057=(a057+a061);
  a061=casadi_sq(a056);
  a062=(a057*a061);
  a028=(a028+a062);
  a062=(a027*a028);
  a063=cos(a052);
  a064=(a062*a063);
  a065=cos(a054);
  a066=(a064*a065);
  a006=(a006-a066);
  a066=1.2622483000000001e+01;
  a067=1.1211672000000000e+01;
  a068=(a067*a036);
  a066=(a066+a068);
  a068=-2.8836583999999998e+01;
  a069=(a068*a038);
  a066=(a066+a069);
  a069=2.6861415999999998e+01;
  a070=(a069*a040);
  a066=(a066+a070);
  a070=(a066*a052);
  a071=1.4340211000000000e+01;
  a072=-1.0152808899999999e+02;
  a073=(a072*a036);
  a071=(a071+a073);
  a073=1.4161946200000000e+02;
  a074=(a073*a038);
  a071=(a071+a074);
  a074=-5.3997655999999999e+01;
  a075=(a074*a040);
  a071=(a071+a075);
  a075=(a053*a052);
  a076=(a071*a075);
  a070=(a070+a076);
  a076=-3.1844681800000001e+02;
  a077=7.2491903100000002e+02;
  a078=(a077*a036);
  a076=(a076+a078);
  a078=-1.9602528030000001e+03;
  a079=(a078*a038);
  a076=(a076+a079);
  a079=1.7332038110000001e+03;
  a080=(a079*a040);
  a076=(a076+a080);
  a080=(a075*a053);
  a081=(a076*a080);
  a070=(a070+a081);
  a081=7.1868526499999996e+02;
  a082=-1.7523918999999999e+01;
  a083=(a082*a036);
  a081=(a081+a083);
  a083=6.5252556180000001e+03;
  a084=(a083*a038);
  a081=(a081+a084);
  a084=-8.1779472100000003e+03;
  a085=(a084*a040);
  a081=(a081+a085);
  a085=(a080*a053);
  a086=(a081*a085);
  a070=(a070+a086);
  a086=3.2297709999999999e+00;
  a087=1.0991650999999999e+01;
  a088=(a087*a036);
  a086=(a086+a088);
  a088=-2.9369515000000000e+01;
  a089=(a088*a038);
  a086=(a086+a089);
  a089=2.6266324999999998e+01;
  a090=(a089*a040);
  a086=(a086+a090);
  a090=arg[4]? arg[4][0] : 0;
  a091=(a086*a090);
  a092=3.1419312999999999e+01;
  a093=-2.1712130999999999e+02;
  a094=(a093*a036);
  a092=(a092+a094);
  a094=3.9809161499999999e+02;
  a095=(a094*a038);
  a092=(a092+a095);
  a095=-2.0738472999999999e+02;
  a096=(a095*a040);
  a092=(a092+a096);
  a096=casadi_sq(a090);
  a097=(a096*a090);
  a098=(a092*a097);
  a091=(a091+a098);
  a098=-6.3957199500000002e+02;
  a099=1.9119816610000000e+03;
  a100=(a099*a036);
  a098=(a098+a100);
  a100=-2.9751745470000001e+03;
  a101=(a100*a038);
  a098=(a098+a101);
  a101=1.2345741399999999e+03;
  a102=(a101*a040);
  a098=(a098+a102);
  a102=(a097*a096);
  a103=(a098*a102);
  a091=(a091+a103);
  a103=2.4384083030000002e+03;
  a104=-3.1924757900000000e+03;
  a105=(a104*a036);
  a103=(a103+a105);
  a105=3.2756856130000001e+03;
  a106=(a105*a038);
  a103=(a103+a106);
  a106=-3.5469790100000000e+02;
  a107=(a106*a040);
  a103=(a103+a107);
  a096=(a102*a096);
  a107=(a103*a096);
  a091=(a091+a107);
  a070=(a070+a091);
  a091=(a027*a070);
  a107=sin(a052);
  a108=(a091*a107);
  a006=(a006+a108);
  a109=(a066*a054);
  a110=(a055*a054);
  a111=(a071*a110);
  a109=(a109+a111);
  a111=(a110*a055);
  a112=(a076*a111);
  a109=(a109+a112);
  a112=(a111*a055);
  a113=(a081*a112);
  a109=(a109+a113);
  a113=arg[4]? arg[4][1] : 0;
  a086=(a086*a113);
  a114=casadi_sq(a113);
  a115=(a114*a113);
  a092=(a092*a115);
  a086=(a086+a092);
  a092=(a115*a114);
  a098=(a098*a092);
  a086=(a086+a098);
  a114=(a092*a114);
  a103=(a103*a114);
  a086=(a086+a103);
  a109=(a109+a086);
  a086=(a027*a109);
  a103=sin(a054);
  a098=(a086*a103);
  a006=(a006+a098);
  a116=arg[4]? arg[4][3] : 0;
  a117=1.0000000000000000e-03;
  a116=casadi_fmax(a116,a117);
  a006=(a006/a116);
  if (res[0]!=0) res[0][3]=a006;
  a006=(a062*a103);
  a086=(a086*a065);
  a006=(a006+a086);
  a006=(a006/a116);
  a006=(-a006);
  if (res[0]!=0) res[0][4]=a006;
  a006=(a062*a107);
  a117=(a006*a065);
  a091=(a091*a063);
  a117=(a117+a091);
  a117=(a117/a116);
  a117=(-a117);
  if (res[0]!=0) res[0][5]=a117;
  if (res[0]!=0) res[0][6]=a014;
  a117=1000.;
  a118=arg[0]? arg[0][10] : 0;
  a119=(a117*a118);
  if (res[0]!=0) res[0][7]=a119;
  a119=arg[0]? arg[0][11] : 0;
  a120=(a117*a119);
  if (res[0]!=0) res[0][8]=a120;
  if (res[0]!=0) res[0][9]=a014;
  a120=arg[0]? arg[0][1] : 0;
  a121=cos(a120);
  a122=(a023*a121);
  a123=arg[0]? arg[0][2] : 0;
  a124=cos(a123);
  a125=(a122*a124);
  a126=arg[0]? arg[0][15] : 0;
  a127=(a125+a126);
  if (res[0]!=0) res[0][10]=a127;
  a127=sin(a123);
  a128=(a122*a127);
  a129=arg[0]? arg[0][16] : 0;
  a130=(a128+a129);
  if (res[0]!=0) res[0][11]=a130;
  a130=sin(a120);
  a131=(a023*a130);
  a132=(-a131);
  if (res[0]!=0) res[0][12]=a132;
  a132=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][13]=a132;
  a132=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][14]=a132;
  a132=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][15]=a132;
  a132=arg[1]? arg[1][3] : 0;
  if (res[0]!=0) res[0][16]=a132;
  a132=arg[1]? arg[1][4] : 0;
  if (res[0]!=0) res[0][17]=a132;
  a132=arg[1]? arg[1][5] : 0;
  if (res[0]!=0) res[0][18]=a132;
  a132=arg[1]? arg[1][6] : 0;
  if (res[0]!=0) res[0][19]=a132;
  a132=arg[1]? arg[1][7] : 0;
  if (res[0]!=0) res[0][20]=a132;
  a132=arg[1]? arg[1][8] : 0;
  if (res[0]!=0) res[0][21]=a132;
  a132=arg[1]? arg[1][9] : 0;
  if (res[0]!=0) res[0][22]=a132;
  a132=arg[1]? arg[1][10] : 0;
  if (res[0]!=0) res[0][23]=a132;
  a132=arg[1]? arg[1][11] : 0;
  if (res[0]!=0) res[0][24]=a132;
  a132=arg[1]? arg[1][12] : 0;
  if (res[0]!=0) res[0][25]=a132;
  a132=arg[1]? arg[1][13] : 0;
  if (res[0]!=0) res[0][26]=a132;
  a132=arg[1]? arg[1][14] : 0;
  if (res[0]!=0) res[0][27]=a132;
  a132=arg[1]? arg[1][15] : 0;
  if (res[0]!=0) res[0][28]=a132;
  a132=arg[1]? arg[1][16] : 0;
  if (res[0]!=0) res[0][29]=a132;
  if (res[0]!=0) res[0][30]=a023;
  if (res[0]!=0) res[0][31]=a120;
  if (res[0]!=0) res[0][32]=a123;
  if (res[0]!=0) res[0][33]=a000;
  if (res[0]!=0) res[0][34]=a002;
  if (res[0]!=0) res[0][35]=a004;
  if (res[0]!=0) res[0][36]=a052;
  if (res[0]!=0) res[0][37]=a054;
  a004=arg[0]? arg[0][8] : 0;
  if (res[0]!=0) res[0][38]=a004;
  if (res[0]!=0) res[0][39]=a013;
  if (res[0]!=0) res[0][40]=a118;
  if (res[0]!=0) res[0][41]=a119;
  if (res[0]!=0) res[0][42]=a001;
  if (res[0]!=0) res[0][43]=a003;
  if (res[0]!=0) res[0][44]=a005;
  if (res[0]!=0) res[0][45]=a126;
  if (res[0]!=0) res[0][46]=a129;
  if (res[1]!=0) res[1][0]=a024;
  if (res[1]!=0) res[1][1]=a024;
  if (res[1]!=0) res[1][2]=a024;
  if (res[1]!=0) res[1][3]=a024;
  if (res[1]!=0) res[1][4]=a024;
  if (res[1]!=0) res[1][5]=a024;
  a129=(a024<=a023);
  a023=(a023<=a024);
  a023=(a129+a023);
  a129=(a129/a023);
  a022=(a022*a129);
  a022=(a025*a022);
  a026=(a026*a129);
  a022=(a022+a026);
  a022=(a007*a022);
  a026=(a070*a022);
  a023=(a033<=a035);
  a035=(a035<=a033);
  a035=(a023+a035);
  a023=(a023/a035);
  a035=(a034<=a024);
  a034=(a024<=a034);
  a034=(a035+a034);
  a035=(a035/a034);
  a034=(a033<=a032);
  a032=(a032<=a033);
  a032=(a034+a032);
  a034=(a034/a032);
  a032=(a031<=a024);
  a033=(a024<=a031);
  a033=(a032+a033);
  a032=(a032/a033);
  a129=(a129/a018);
  a129=(a032*a129);
  a129=(a034*a129);
  a129=(a035*a129);
  a129=(a023*a129);
  a033=(a067*a129);
  a126=(a036+a036);
  a005=(a126*a129);
  a003=(a068*a005);
  a033=(a033+a003);
  a003=(a036*a005);
  a001=(a038*a129);
  a003=(a003+a001);
  a001=(a069*a003);
  a033=(a033+a001);
  a001=(a052*a033);
  a119=(a072*a129);
  a118=(a073*a005);
  a119=(a119+a118);
  a118=(a074*a003);
  a119=(a119+a118);
  a118=(a075*a119);
  a001=(a001+a118);
  a118=(a077*a129);
  a013=(a078*a005);
  a118=(a118+a013);
  a013=(a079*a003);
  a118=(a118+a013);
  a013=(a080*a118);
  a001=(a001+a013);
  a013=(a082*a129);
  a004=(a083*a005);
  a013=(a013+a004);
  a004=(a084*a003);
  a013=(a013+a004);
  a004=(a085*a013);
  a001=(a001+a004);
  a004=(a087*a129);
  a002=(a088*a005);
  a004=(a004+a002);
  a002=(a089*a003);
  a004=(a004+a002);
  a002=(a090*a004);
  a000=(a093*a129);
  a123=(a094*a005);
  a000=(a000+a123);
  a123=(a095*a003);
  a000=(a000+a123);
  a123=(a097*a000);
  a002=(a002+a123);
  a123=(a099*a129);
  a120=(a100*a005);
  a123=(a123+a120);
  a120=(a101*a003);
  a123=(a123+a120);
  a120=(a102*a123);
  a002=(a002+a120);
  a120=(a104*a129);
  a132=(a105*a005);
  a120=(a120+a132);
  a132=(a106*a003);
  a120=(a120+a132);
  a132=(a096*a120);
  a002=(a002+a132);
  a001=(a001+a002);
  a001=(a027*a001);
  a026=(a026+a001);
  a001=(a107*a026);
  a002=(a028*a022);
  a132=(a029*a129);
  a133=(a037*a005);
  a132=(a132+a133);
  a133=(a039*a003);
  a132=(a132+a133);
  a133=(a036*a003);
  a134=(a040*a129);
  a133=(a133+a134);
  a134=(a041*a133);
  a132=(a132+a134);
  a133=(a036*a133);
  a134=(a042*a129);
  a133=(a133+a134);
  a134=(a043*a133);
  a132=(a132+a134);
  a133=(a036*a133);
  a134=(a044*a129);
  a133=(a133+a134);
  a134=(a045*a133);
  a132=(a132+a134);
  a133=(a036*a133);
  a134=(a046*a129);
  a133=(a133+a134);
  a133=(a047*a133);
  a132=(a132+a133);
  a133=(a049*a129);
  a134=(a050*a005);
  a133=(a133+a134);
  a134=(a051*a003);
  a133=(a133+a134);
  a133=(a056*a133);
  a132=(a132+a133);
  a129=(a058*a129);
  a005=(a059*a005);
  a129=(a129+a005);
  a003=(a060*a003);
  a129=(a129+a003);
  a129=(a061*a129);
  a132=(a132+a129);
  a132=(a027*a132);
  a002=(a002+a132);
  a132=(a063*a002);
  a132=(a065*a132);
  a001=(a001-a132);
  a022=(a109*a022);
  a033=(a054*a033);
  a119=(a110*a119);
  a033=(a033+a119);
  a118=(a111*a118);
  a033=(a033+a118);
  a013=(a112*a013);
  a033=(a033+a013);
  a004=(a113*a004);
  a000=(a115*a000);
  a004=(a004+a000);
  a123=(a092*a123);
  a004=(a004+a123);
  a120=(a114*a120);
  a004=(a004+a120);
  a033=(a033+a004);
  a033=(a027*a033);
  a022=(a022+a033);
  a033=(a103*a022);
  a001=(a001+a033);
  a001=(a001/a116);
  if (res[1]!=0) res[1][6]=a001;
  a001=(a052+a052);
  a033=(a052*a001);
  a033=(a033+a053);
  a004=(a071*a033);
  a004=(a066+a004);
  a033=(a053*a033);
  a120=(a075*a001);
  a033=(a033+a120);
  a120=(a076*a033);
  a004=(a004+a120);
  a053=(a053*a033);
  a033=(a080*a001);
  a053=(a053+a033);
  a053=(a081*a053);
  a004=(a004+a053);
  a004=(a027*a004);
  a053=(a107*a004);
  a053=(a053+a091);
  a091=(a048*a001);
  a033=(a056+a056);
  a001=(a033*a001);
  a001=(a057*a001);
  a091=(a091+a001);
  a091=(a027*a091);
  a001=(a063*a091);
  a001=(a001-a006);
  a001=(a065*a001);
  a053=(a053-a001);
  a053=(a053/a116);
  if (res[1]!=0) res[1][7]=a053;
  a053=(a054+a054);
  a001=(a054*a053);
  a001=(a001+a055);
  a071=(a071*a001);
  a066=(a066+a071);
  a001=(a055*a001);
  a071=(a110*a053);
  a001=(a001+a071);
  a076=(a076*a001);
  a066=(a066+a076);
  a055=(a055*a001);
  a001=(a111*a053);
  a055=(a055+a001);
  a081=(a081*a055);
  a066=(a066+a081);
  a066=(a027*a066);
  a081=(a103*a066);
  a081=(a081+a086);
  a048=(a048*a053);
  a033=(a033*a053);
  a057=(a057*a033);
  a048=(a048+a057);
  a048=(a027*a048);
  a057=(a063*a048);
  a057=(a065*a057);
  a033=(a064*a103);
  a057=(a057-a033);
  a081=(a081-a057);
  a081=(a081/a116);
  if (res[1]!=0) res[1][8]=a081;
  a031=(a031/a018);
  a081=(a017<=a016);
  a016=(a016<=a017);
  a016=(a081+a016);
  a081=(a081/a016);
  a016=(a015<=a014);
  a014=(a014<=a015);
  a014=(a016+a014);
  a016=(a016/a014);
  a016=(a012*a016);
  a011=(a011*a016);
  a081=(a081*a011);
  a030=(a030*a081);
  a018=(a018+a018);
  a030=(a030/a018);
  a031=(a031*a030);
  a032=(a032*a031);
  a034=(a034*a032);
  a035=(a035*a034);
  a023=(a023*a035);
  a067=(a067*a023);
  a126=(a126*a023);
  a068=(a068*a126);
  a067=(a067+a068);
  a068=(a036*a126);
  a038=(a038*a023);
  a068=(a068+a038);
  a069=(a069*a068);
  a067=(a067+a069);
  a052=(a052*a067);
  a072=(a072*a023);
  a073=(a073*a126);
  a072=(a072+a073);
  a074=(a074*a068);
  a072=(a072+a074);
  a075=(a075*a072);
  a052=(a052+a075);
  a077=(a077*a023);
  a078=(a078*a126);
  a077=(a077+a078);
  a079=(a079*a068);
  a077=(a077+a079);
  a080=(a080*a077);
  a052=(a052+a080);
  a082=(a082*a023);
  a083=(a083*a126);
  a082=(a082+a083);
  a084=(a084*a068);
  a082=(a082+a084);
  a085=(a085*a082);
  a052=(a052+a085);
  a087=(a087*a023);
  a088=(a088*a126);
  a087=(a087+a088);
  a089=(a089*a068);
  a087=(a087+a089);
  a090=(a090*a087);
  a093=(a093*a023);
  a094=(a094*a126);
  a093=(a093+a094);
  a095=(a095*a068);
  a093=(a093+a095);
  a097=(a097*a093);
  a090=(a090+a097);
  a099=(a099*a023);
  a100=(a100*a126);
  a099=(a099+a100);
  a101=(a101*a068);
  a099=(a099+a101);
  a102=(a102*a099);
  a090=(a090+a102);
  a104=(a104*a023);
  a105=(a105*a126);
  a104=(a104+a105);
  a106=(a106*a068);
  a104=(a104+a106);
  a096=(a096*a104);
  a090=(a090+a096);
  a052=(a052+a090);
  a052=(a027*a052);
  a090=(a021<=a020);
  a020=(a020<=a021);
  a020=(a090+a020);
  a090=(a090/a020);
  a020=3.2559323623598138e+00;
  a010=pow(a010,a020);
  a019=(a019*a010);
  a010=3.4704147145583901e-03;
  a010=(a010*a081);
  a019=(a019*a010);
  a009=(a009*a019);
  a090=(a090*a009);
  a008=(a008*a090);
  a008=(a025*a008);
  a025=(a025*a008);
  a007=(a007*a025);
  a070=(a070*a007);
  a052=(a052-a070);
  a070=(a107*a052);
  a029=(a029*a023);
  a037=(a037*a126);
  a029=(a029+a037);
  a039=(a039*a068);
  a029=(a029+a039);
  a039=(a036*a068);
  a040=(a040*a023);
  a039=(a039+a040);
  a041=(a041*a039);
  a029=(a029+a041);
  a039=(a036*a039);
  a042=(a042*a023);
  a039=(a039+a042);
  a043=(a043*a039);
  a029=(a029+a043);
  a039=(a036*a039);
  a044=(a044*a023);
  a039=(a039+a044);
  a045=(a045*a039);
  a029=(a029+a045);
  a036=(a036*a039);
  a046=(a046*a023);
  a036=(a036+a046);
  a047=(a047*a036);
  a029=(a029+a047);
  a049=(a049*a023);
  a050=(a050*a126);
  a049=(a049+a050);
  a051=(a051*a068);
  a049=(a049+a051);
  a056=(a056*a049);
  a029=(a029+a056);
  a058=(a058*a023);
  a059=(a059*a126);
  a058=(a058+a059);
  a060=(a060*a068);
  a058=(a058+a060);
  a061=(a061*a058);
  a029=(a029+a061);
  a029=(a027*a029);
  a028=(a028*a007);
  a029=(a029-a028);
  a028=(a063*a029);
  a028=(a065*a028);
  a070=(a070-a028);
  a054=(a054*a067);
  a110=(a110*a072);
  a054=(a054+a110);
  a111=(a111*a077);
  a054=(a054+a111);
  a112=(a112*a082);
  a054=(a054+a112);
  a113=(a113*a087);
  a115=(a115*a093);
  a113=(a113+a115);
  a092=(a092*a099);
  a113=(a113+a092);
  a114=(a114*a104);
  a113=(a113+a114);
  a054=(a054+a113);
  a027=(a027*a054);
  a109=(a109*a007);
  a027=(a027-a109);
  a109=(a103*a027);
  a070=(a070+a109);
  a070=(a070/a116);
  if (res[1]!=0) res[1][9]=a070;
  a070=(a103*a002);
  a022=(a065*a022);
  a070=(a070+a022);
  a070=(a070/a116);
  a070=(-a070);
  if (res[1]!=0) res[1][10]=a070;
  a070=(a103*a091);
  a070=(a070/a116);
  a070=(-a070);
  if (res[1]!=0) res[1][11]=a070;
  a070=(a103*a048);
  a062=(a062*a065);
  a070=(a070+a062);
  a066=(a065*a066);
  a066=(a066-a098);
  a070=(a070+a066);
  a070=(a070/a116);
  a070=(-a070);
  if (res[1]!=0) res[1][12]=a070;
  a070=(a103*a029);
  a027=(a065*a027);
  a070=(a070+a027);
  a070=(a070/a116);
  a070=(-a070);
  if (res[1]!=0) res[1][13]=a070;
  a002=(a107*a002);
  a002=(a065*a002);
  a026=(a063*a026);
  a002=(a002+a026);
  a002=(a002/a116);
  a002=(-a002);
  if (res[1]!=0) res[1][14]=a002;
  a091=(a107*a091);
  a091=(a091+a064);
  a091=(a065*a091);
  a004=(a063*a004);
  a004=(a004-a108);
  a091=(a091+a004);
  a091=(a091/a116);
  a091=(-a091);
  if (res[1]!=0) res[1][15]=a091;
  a048=(a107*a048);
  a048=(a065*a048);
  a006=(a006*a103);
  a048=(a048-a006);
  a048=(a048/a116);
  a048=(-a048);
  if (res[1]!=0) res[1][16]=a048;
  a107=(a107*a029);
  a065=(a065*a107);
  a063=(a063*a052);
  a065=(a065+a063);
  a065=(a065/a116);
  a065=(-a065);
  if (res[1]!=0) res[1][17]=a065;
  if (res[1]!=0) res[1][18]=a012;
  if (res[1]!=0) res[1][19]=a117;
  if (res[1]!=0) res[1][20]=a117;
  if (res[1]!=0) res[1][21]=a012;
  a012=(a124*a121);
  if (res[1]!=0) res[1][22]=a012;
  a124=(a124*a131);
  a124=(-a124);
  if (res[1]!=0) res[1][23]=a124;
  a128=(-a128);
  if (res[1]!=0) res[1][24]=a128;
  if (res[1]!=0) res[1][25]=a024;
  a121=(a127*a121);
  if (res[1]!=0) res[1][26]=a121;
  a127=(a127*a131);
  a127=(-a127);
  if (res[1]!=0) res[1][27]=a127;
  if (res[1]!=0) res[1][28]=a125;
  if (res[1]!=0) res[1][29]=a024;
  a130=(-a130);
  if (res[1]!=0) res[1][30]=a130;
  a122=(-a122);
  if (res[1]!=0) res[1][31]=a122;
  if (res[1]!=0) res[1][32]=a024;
  if (res[1]!=0) res[1][33]=a024;
  if (res[1]!=0) res[1][34]=a024;
  if (res[1]!=0) res[1][35]=a024;
  if (res[1]!=0) res[1][36]=a024;
  if (res[1]!=0) res[1][37]=a024;
  if (res[1]!=0) res[1][38]=a024;
  if (res[1]!=0) res[1][39]=a024;
  if (res[1]!=0) res[1][40]=a024;
  if (res[1]!=0) res[1][41]=a024;
  if (res[1]!=0) res[1][42]=a024;
  if (res[1]!=0) res[1][43]=a024;
  if (res[1]!=0) res[1][44]=a024;
  if (res[1]!=0) res[1][45]=a024;
  if (res[1]!=0) res[1][46]=a024;
  if (res[1]!=0) res[1][47]=a024;
  if (res[1]!=0) res[1][48]=a024;
  if (res[1]!=0) res[1][49]=a024;
  if (res[1]!=0) res[1][50]=a024;
  if (res[1]!=0) res[1][51]=a024;
  if (res[1]!=0) res[1][52]=a024;
  if (res[1]!=0) res[1][53]=a024;
  if (res[1]!=0) res[1][54]=a024;
  if (res[1]!=0) res[1][55]=a024;
  if (res[1]!=0) res[1][56]=a024;
  if (res[1]!=0) res[1][57]=a024;
  if (res[1]!=0) res[1][58]=a024;
  if (res[1]!=0) res[1][59]=a024;
  if (res[1]!=0) res[1][60]=a024;
  if (res[1]!=0) res[1][61]=a024;
  if (res[1]!=0) res[1][62]=a024;
  if (res[1]!=0) res[1][63]=a024;
  if (res[1]!=0) res[1][64]=a024;
  if (res[1]!=0) res[1][65]=a024;
  return 0;
}

CASADI_SYMBOL_EXPORT int m130_mhe_cost_y_0_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int m130_mhe_cost_y_0_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int m130_mhe_cost_y_0_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void m130_mhe_cost_y_0_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int m130_mhe_cost_y_0_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void m130_mhe_cost_y_0_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void m130_mhe_cost_y_0_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void m130_mhe_cost_y_0_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int m130_mhe_cost_y_0_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int m130_mhe_cost_y_0_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real m130_mhe_cost_y_0_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* m130_mhe_cost_y_0_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* m130_mhe_cost_y_0_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* m130_mhe_cost_y_0_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* m130_mhe_cost_y_0_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int m130_mhe_cost_y_0_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int m130_mhe_cost_y_0_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
