/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) m130_mhe_cost_y_0_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {17, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {9, 1, 1};
static const casadi_int casadi_s4[3] = {47, 1, 1};

/* m130_mhe_cost_y_0_fun:(i0[17],i1[17],i2[0],i3[],i4[9])->(o0[47]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32;
  a00=arg[0]? arg[0][3] : 0;
  a01=arg[0]? arg[0][12] : 0;
  a02=(a00+a01);
  if (res[0]!=0) res[0][0]=a02;
  a02=arg[0]? arg[0][4] : 0;
  a03=arg[0]? arg[0][13] : 0;
  a04=(a02+a03);
  if (res[0]!=0) res[0][1]=a04;
  a04=arg[0]? arg[0][5] : 0;
  a05=arg[0]? arg[0][14] : 0;
  a06=(a04+a05);
  if (res[0]!=0) res[0][2]=a06;
  a06=arg[4]? arg[4][4] : 0;
  a07=1.3270000000000001e-02;
  a08=5.0000000000000000e-01;
  a09=1.2250000000000001e+00;
  a10=2.8814999999999998e+02;
  a11=6.4999999999999997e-03;
  a12=100.;
  a13=arg[0]? arg[0][9] : 0;
  a12=(a12*a13);
  a14=arg[4]? arg[4][8] : 0;
  a12=(a12+a14);
  a14=0.;
  a14=casadi_fmax(a12,a14);
  a11=(a11*a14);
  a11=(a10-a11);
  a14=2.1665000000000001e+02;
  a11=casadi_fmax(a11,a14);
  a10=(a11/a10);
  a14=4.2559323623598138e+00;
  a10=pow(a10,a14);
  a09=(a09*a10);
  a10=1.0000000000000000e-10;
  a09=casadi_fmax(a09,a10);
  a09=(a08*a09);
  a10=arg[0]? arg[0][0] : 0;
  a09=(a09*a10);
  a09=(a09*a10);
  a14=1.;
  a15=7.5000000000000000e+00;
  a15=(a10-a15);
  a16=1.5000000000000000e+00;
  a15=(a15/a16);
  a15=tanh(a15);
  a15=(a14+a15);
  a08=(a08*a15);
  a09=(a09*a08);
  a07=(a07*a09);
  a09=6.4465099999999997e-01;
  a08=-6.6772809999999998e+00;
  a15=casadi_fmax(a10,a14);
  a16=4.0187000000000000e+02;
  a16=(a16*a11);
  a16=sqrt(a16);
  a15=(a15/a16);
  a15=casadi_fmin(a15,a14);
  a16=1.0000000000000001e-01;
  a15=casadi_fmax(a15,a16);
  a15=casadi_fmin(a15,a14);
  a15=casadi_fmax(a15,a16);
  a08=(a08*a15);
  a09=(a09+a08);
  a08=5.6985242999999997e+01;
  a16=casadi_sq(a15);
  a08=(a08*a16);
  a09=(a09+a08);
  a08=-2.5248384700000000e+02;
  a14=(a16*a15);
  a08=(a08*a14);
  a09=(a09+a08);
  a08=6.1561736499999995e+02;
  a11=(a14*a15);
  a08=(a08*a11);
  a09=(a09+a08);
  a08=-8.3459076500000003e+02;
  a11=(a11*a15);
  a08=(a08*a11);
  a09=(a09+a08);
  a08=5.8734720100000004e+02;
  a11=(a11*a15);
  a08=(a08*a11);
  a09=(a09+a08);
  a08=-1.6562689000000000e+02;
  a11=(a11*a15);
  a08=(a08*a11);
  a09=(a09+a08);
  a08=5.6522999999999997e-02;
  a11=-9.9855799999999995e-01;
  a11=(a11*a15);
  a08=(a08+a11);
  a11=2.3926500000000002e+00;
  a11=(a11*a16);
  a08=(a08+a11);
  a11=-1.7378279999999999e+00;
  a11=(a11*a14);
  a08=(a08+a11);
  a11=arg[0]? arg[0][6] : 0;
  a17=casadi_sq(a11);
  a18=arg[0]? arg[0][7] : 0;
  a19=casadi_sq(a18);
  a20=(a17+a19);
  a08=(a08*a20);
  a09=(a09+a08);
  a08=-3.0486789999999999e+00;
  a21=5.4473490000000000e+00;
  a21=(a21*a15);
  a08=(a08+a21);
  a21=-9.6709250000000004e+00;
  a21=(a21*a16);
  a08=(a08+a21);
  a21=4.8268709999999997e+00;
  a21=(a21*a14);
  a08=(a08+a21);
  a20=casadi_sq(a20);
  a08=(a08*a20);
  a09=(a09+a08);
  a09=(a07*a09);
  a08=cos(a11);
  a20=(a09*a08);
  a21=cos(a18);
  a20=(a20*a21);
  a06=(a06-a20);
  a20=1.2622483000000001e+01;
  a22=1.1211672000000000e+01;
  a22=(a22*a15);
  a20=(a20+a22);
  a22=-2.8836583999999998e+01;
  a22=(a22*a16);
  a20=(a20+a22);
  a22=2.6861415999999998e+01;
  a22=(a22*a14);
  a20=(a20+a22);
  a22=(a20*a11);
  a23=1.4340211000000000e+01;
  a24=-1.0152808899999999e+02;
  a24=(a24*a15);
  a23=(a23+a24);
  a24=1.4161946200000000e+02;
  a24=(a24*a16);
  a23=(a23+a24);
  a24=-5.3997655999999999e+01;
  a24=(a24*a14);
  a23=(a23+a24);
  a24=(a17*a11);
  a25=(a23*a24);
  a22=(a22+a25);
  a25=-3.1844681800000001e+02;
  a26=7.2491903100000002e+02;
  a26=(a26*a15);
  a25=(a25+a26);
  a26=-1.9602528030000001e+03;
  a26=(a26*a16);
  a25=(a25+a26);
  a26=1.7332038110000001e+03;
  a26=(a26*a14);
  a25=(a25+a26);
  a24=(a24*a17);
  a26=(a25*a24);
  a22=(a22+a26);
  a26=7.1868526499999996e+02;
  a27=-1.7523918999999999e+01;
  a27=(a27*a15);
  a26=(a26+a27);
  a27=6.5252556180000001e+03;
  a27=(a27*a16);
  a26=(a26+a27);
  a27=-8.1779472100000003e+03;
  a27=(a27*a14);
  a26=(a26+a27);
  a24=(a24*a17);
  a24=(a26*a24);
  a22=(a22+a24);
  a24=3.2297709999999999e+00;
  a17=1.0991650999999999e+01;
  a17=(a17*a15);
  a24=(a24+a17);
  a17=-2.9369515000000000e+01;
  a17=(a17*a16);
  a24=(a24+a17);
  a17=2.6266324999999998e+01;
  a17=(a17*a14);
  a24=(a24+a17);
  a17=arg[4]? arg[4][0] : 0;
  a27=(a24*a17);
  a28=3.1419312999999999e+01;
  a29=-2.1712130999999999e+02;
  a29=(a29*a15);
  a28=(a28+a29);
  a29=3.9809161499999999e+02;
  a29=(a29*a16);
  a28=(a28+a29);
  a29=-2.0738472999999999e+02;
  a29=(a29*a14);
  a28=(a28+a29);
  a29=casadi_sq(a17);
  a17=(a29*a17);
  a30=(a28*a17);
  a27=(a27+a30);
  a30=-6.3957199500000002e+02;
  a31=1.9119816610000000e+03;
  a31=(a31*a15);
  a30=(a30+a31);
  a31=-2.9751745470000001e+03;
  a31=(a31*a16);
  a30=(a30+a31);
  a31=1.2345741399999999e+03;
  a31=(a31*a14);
  a30=(a30+a31);
  a17=(a17*a29);
  a31=(a30*a17);
  a27=(a27+a31);
  a31=2.4384083030000002e+03;
  a32=-3.1924757900000000e+03;
  a32=(a32*a15);
  a31=(a31+a32);
  a32=3.2756856130000001e+03;
  a32=(a32*a16);
  a31=(a31+a32);
  a32=-3.5469790100000000e+02;
  a32=(a32*a14);
  a31=(a31+a32);
  a17=(a17*a29);
  a17=(a31*a17);
  a27=(a27+a17);
  a22=(a22+a27);
  a22=(a07*a22);
  a27=sin(a11);
  a17=(a22*a27);
  a06=(a06+a17);
  a20=(a20*a18);
  a17=(a19*a18);
  a23=(a23*a17);
  a20=(a20+a23);
  a17=(a17*a19);
  a25=(a25*a17);
  a20=(a20+a25);
  a17=(a17*a19);
  a26=(a26*a17);
  a20=(a20+a26);
  a26=arg[4]? arg[4][1] : 0;
  a24=(a24*a26);
  a17=casadi_sq(a26);
  a26=(a17*a26);
  a28=(a28*a26);
  a24=(a24+a28);
  a26=(a26*a17);
  a30=(a30*a26);
  a24=(a24+a30);
  a26=(a26*a17);
  a31=(a31*a26);
  a24=(a24+a31);
  a20=(a20+a24);
  a07=(a07*a20);
  a20=sin(a18);
  a24=(a07*a20);
  a06=(a06+a24);
  a24=arg[4]? arg[4][3] : 0;
  a31=1.0000000000000000e-03;
  a24=casadi_fmax(a24,a31);
  a06=(a06/a24);
  if (res[0]!=0) res[0][3]=a06;
  a20=(a09*a20);
  a07=(a07*a21);
  a20=(a20+a07);
  a20=(a20/a24);
  a20=(-a20);
  if (res[0]!=0) res[0][4]=a20;
  a09=(a09*a27);
  a09=(a09*a21);
  a22=(a22*a08);
  a09=(a09+a22);
  a09=(a09/a24);
  a09=(-a09);
  if (res[0]!=0) res[0][5]=a09;
  if (res[0]!=0) res[0][6]=a12;
  a09=1000.;
  a24=arg[0]? arg[0][10] : 0;
  a22=(a09*a24);
  if (res[0]!=0) res[0][7]=a22;
  a22=arg[0]? arg[0][11] : 0;
  a09=(a09*a22);
  if (res[0]!=0) res[0][8]=a09;
  if (res[0]!=0) res[0][9]=a12;
  a12=arg[0]? arg[0][1] : 0;
  a09=cos(a12);
  a09=(a10*a09);
  a08=arg[0]? arg[0][2] : 0;
  a21=cos(a08);
  a21=(a09*a21);
  a27=arg[0]? arg[0][15] : 0;
  a21=(a21+a27);
  if (res[0]!=0) res[0][10]=a21;
  a21=sin(a08);
  a09=(a09*a21);
  a21=arg[0]? arg[0][16] : 0;
  a09=(a09+a21);
  if (res[0]!=0) res[0][11]=a09;
  a09=sin(a12);
  a09=(a10*a09);
  a09=(-a09);
  if (res[0]!=0) res[0][12]=a09;
  a09=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][13]=a09;
  a09=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][14]=a09;
  a09=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][15]=a09;
  a09=arg[1]? arg[1][3] : 0;
  if (res[0]!=0) res[0][16]=a09;
  a09=arg[1]? arg[1][4] : 0;
  if (res[0]!=0) res[0][17]=a09;
  a09=arg[1]? arg[1][5] : 0;
  if (res[0]!=0) res[0][18]=a09;
  a09=arg[1]? arg[1][6] : 0;
  if (res[0]!=0) res[0][19]=a09;
  a09=arg[1]? arg[1][7] : 0;
  if (res[0]!=0) res[0][20]=a09;
  a09=arg[1]? arg[1][8] : 0;
  if (res[0]!=0) res[0][21]=a09;
  a09=arg[1]? arg[1][9] : 0;
  if (res[0]!=0) res[0][22]=a09;
  a09=arg[1]? arg[1][10] : 0;
  if (res[0]!=0) res[0][23]=a09;
  a09=arg[1]? arg[1][11] : 0;
  if (res[0]!=0) res[0][24]=a09;
  a09=arg[1]? arg[1][12] : 0;
  if (res[0]!=0) res[0][25]=a09;
  a09=arg[1]? arg[1][13] : 0;
  if (res[0]!=0) res[0][26]=a09;
  a09=arg[1]? arg[1][14] : 0;
  if (res[0]!=0) res[0][27]=a09;
  a09=arg[1]? arg[1][15] : 0;
  if (res[0]!=0) res[0][28]=a09;
  a09=arg[1]? arg[1][16] : 0;
  if (res[0]!=0) res[0][29]=a09;
  if (res[0]!=0) res[0][30]=a10;
  if (res[0]!=0) res[0][31]=a12;
  if (res[0]!=0) res[0][32]=a08;
  if (res[0]!=0) res[0][33]=a00;
  if (res[0]!=0) res[0][34]=a02;
  if (res[0]!=0) res[0][35]=a04;
  if (res[0]!=0) res[0][36]=a11;
  if (res[0]!=0) res[0][37]=a18;
  a18=arg[0]? arg[0][8] : 0;
  if (res[0]!=0) res[0][38]=a18;
  if (res[0]!=0) res[0][39]=a13;
  if (res[0]!=0) res[0][40]=a24;
  if (res[0]!=0) res[0][41]=a22;
  if (res[0]!=0) res[0][42]=a01;
  if (res[0]!=0) res[0][43]=a03;
  if (res[0]!=0) res[0][44]=a05;
  if (res[0]!=0) res[0][45]=a27;
  if (res[0]!=0) res[0][46]=a21;
  return 0;
}

CASADI_SYMBOL_EXPORT int m130_mhe_cost_y_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int m130_mhe_cost_y_0_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int m130_mhe_cost_y_0_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void m130_mhe_cost_y_0_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int m130_mhe_cost_y_0_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void m130_mhe_cost_y_0_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void m130_mhe_cost_y_0_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void m130_mhe_cost_y_0_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int m130_mhe_cost_y_0_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int m130_mhe_cost_y_0_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real m130_mhe_cost_y_0_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* m130_mhe_cost_y_0_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* m130_mhe_cost_y_0_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* m130_mhe_cost_y_0_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* m130_mhe_cost_y_0_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int m130_mhe_cost_y_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int m130_mhe_cost_y_0_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
