/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) m130_mhe_cost_y_0_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {17, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {9, 1, 1};
static const casadi_int casadi_s4[3] = {47, 1, 1};
static const casadi_int casadi_s5[116] = 
  {34, 47, 0, 2, 4, 6, 10, 14,
  18, 19, 20, 21, 22, 26, 30, 32,
  33, 34, 35, 36, 37, 38, 39, 40,
  41, 42, 43, 44, 45, 46, 47, 48,
  49, 50, 51, 52, 53, 54, 55, 56,
  57, 58, 59, 60, 61, 62, 63, 64,
  65, 66, 20, 29, 21, 30, 22, 31,
  17, 23, 24, 26, 17, 23, 24, 26,
  17, 23, 24, 26, 26, 27, 28, 26,
  17, 18, 19, 32, 17, 18, 19, 33,
  17, 18, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 13,
  14, 15, 16, 17, 18, 19, 20, 21,
  22, 23, 24, 25, 26, 27, 28, 29,
  30, 31, 32, 33};
static const casadi_int casadi_s6[3] = {47, 0, 1};

/* m130_mhe_cost_y_0_fun_jac_ut_xt:(i0[17],i1[17],i2[0],i3[],i4[9])->(o0[47],o1[34x47,66nz],o2[47x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a000, a001, a002, a003, a004, a005, a006, a007, a008, a009, a010, a011;
  casadi_real a012, a013, a014, a015, a016, a017, a018, a019, a020, a021, a022, a023;
  casadi_real a024, a025, a026, a027, a028, a029, a030, a031, a032, a033, a034, a035;
  casadi_real a036, a037, a038, a039, a040, a041, a042, a043, a044, a045, a046, a047;
  casadi_real a048, a049, a050, a051, a052, a053, a054, a055, a056, a057, a058, a059;
  casadi_real a060, a061, a062, a063, a064, a065, a066, a067, a068, a069, a070, a071;
  casadi_real a072, a073, a074, a075, a076, a077, a078, a079, a080, a081, a082, a083;
  casadi_real a084, a085, a086, a087, a088, a089, a090, a091, a092, a093, a094, a095;
  casadi_real a096, a097, a098, a099, a100, a101, a102, a103, a104, a105, a106, a107;
  casadi_real a108, a109, a110, a111, a112, a113, a114, a115, a116, a117, a118, a119;
  casadi_real a120, a121, a122, a123, a124, a125, a126, a127, a128, a129, a130, a131;
  casadi_real a132, a133, a134, a135;
  a000=arg[0]? arg[0][3] : 0;
  a001=arg[0]? arg[0][12] : 0;
  a002=(a000+a001);
  if (res[0]!=0) res[0][0]=a002;
  a002=arg[0]? arg[0][4] : 0;
  a003=arg[0]? arg[0][13] : 0;
  a004=(a002+a003);
  if (res[0]!=0) res[0][1]=a004;
  a004=arg[0]? arg[0][5] : 0;
  a005=arg[0]? arg[0][14] : 0;
  a006=(a004+a005);
  if (res[0]!=0) res[0][2]=a006;
  a006=arg[4]? arg[4][4] : 0;
  a007=1.3270000000000001e-02;
  a008=5.0000000000000000e-01;
  a009=1.2250000000000001e+00;
  a010=2.8814999999999998e+02;
  a011=6.4999999999999997e-03;
  a012=100.;
  a013=arg[0]? arg[0][9] : 0;
  a014=(a012*a013);
  a015=arg[4]? arg[4][8] : 0;
  a014=(a014+a015);
  a015=0.;
  a016=casadi_fmax(a014,a015);
  a016=(a011*a016);
  a016=(a010-a016);
  a017=2.1665000000000001e+02;
  a018=casadi_fmax(a016,a017);
  a010=(a018/a010);
  a019=4.2559323623598138e+00;
  a020=pow(a010,a019);
  a020=(a009*a020);
  a021=1.0000000000000000e-10;
  a022=casadi_fmax(a020,a021);
  a022=(a008*a022);
  a023=arg[0]? arg[0][0] : 0;
  a024=(a022*a023);
  a025=(a024*a023);
  a026=1.;
  a027=7.5000000000000000e+00;
  a027=(a023-a027);
  a028=1.5000000000000000e+00;
  a027=(a027/a028);
  a027=tanh(a027);
  a028=(a026+a027);
  a028=(a008*a028);
  a029=(a025*a028);
  a029=(a007*a029);
  a030=6.4465099999999997e-01;
  a031=-6.6772809999999998e+00;
  a032=casadi_fmax(a023,a026);
  a033=4.0187000000000000e+02;
  a018=(a033*a018);
  a018=sqrt(a018);
  a032=(a032/a018);
  a034=casadi_fmin(a032,a026);
  a035=1.0000000000000001e-01;
  a036=casadi_fmax(a034,a035);
  a037=casadi_fmin(a036,a026);
  a038=casadi_fmax(a037,a035);
  a039=(a031*a038);
  a030=(a030+a039);
  a039=5.6985242999999997e+01;
  a040=casadi_sq(a038);
  a041=(a039*a040);
  a030=(a030+a041);
  a041=-2.5248384700000000e+02;
  a042=(a040*a038);
  a043=(a041*a042);
  a030=(a030+a043);
  a043=6.1561736499999995e+02;
  a044=(a042*a038);
  a045=(a043*a044);
  a030=(a030+a045);
  a045=-8.3459076500000003e+02;
  a046=(a044*a038);
  a047=(a045*a046);
  a030=(a030+a047);
  a047=5.8734720100000004e+02;
  a048=(a046*a038);
  a049=(a047*a048);
  a030=(a030+a049);
  a049=-1.6562689000000000e+02;
  a050=(a048*a038);
  a050=(a049*a050);
  a030=(a030+a050);
  a050=5.6522999999999997e-02;
  a051=-9.9855799999999995e-01;
  a052=(a051*a038);
  a050=(a050+a052);
  a052=2.3926500000000002e+00;
  a053=(a052*a040);
  a050=(a050+a053);
  a053=-1.7378279999999999e+00;
  a054=(a053*a042);
  a050=(a050+a054);
  a054=arg[0]? arg[0][6] : 0;
  a055=casadi_sq(a054);
  a056=arg[0]? arg[0][7] : 0;
  a057=casadi_sq(a056);
  a058=(a055+a057);
  a059=(a050*a058);
  a030=(a030+a059);
  a059=-3.0486789999999999e+00;
  a060=5.4473490000000000e+00;
  a061=(a060*a038);
  a059=(a059+a061);
  a061=-9.6709250000000004e+00;
  a062=(a061*a040);
  a059=(a059+a062);
  a062=4.8268709999999997e+00;
  a063=(a062*a042);
  a059=(a059+a063);
  a063=casadi_sq(a058);
  a064=(a059*a063);
  a030=(a030+a064);
  a064=(a029*a030);
  a065=cos(a054);
  a066=(a064*a065);
  a067=cos(a056);
  a068=(a066*a067);
  a006=(a006-a068);
  a068=1.2622483000000001e+01;
  a069=1.1211672000000000e+01;
  a070=(a069*a038);
  a068=(a068+a070);
  a070=-2.8836583999999998e+01;
  a071=(a070*a040);
  a068=(a068+a071);
  a071=2.6861415999999998e+01;
  a072=(a071*a042);
  a068=(a068+a072);
  a072=(a068*a054);
  a073=1.4340211000000000e+01;
  a074=-1.0152808899999999e+02;
  a075=(a074*a038);
  a073=(a073+a075);
  a075=1.4161946200000000e+02;
  a076=(a075*a040);
  a073=(a073+a076);
  a076=-5.3997655999999999e+01;
  a077=(a076*a042);
  a073=(a073+a077);
  a077=(a055*a054);
  a078=(a073*a077);
  a072=(a072+a078);
  a078=-3.1844681800000001e+02;
  a079=7.2491903100000002e+02;
  a080=(a079*a038);
  a078=(a078+a080);
  a080=-1.9602528030000001e+03;
  a081=(a080*a040);
  a078=(a078+a081);
  a081=1.7332038110000001e+03;
  a082=(a081*a042);
  a078=(a078+a082);
  a082=(a077*a055);
  a083=(a078*a082);
  a072=(a072+a083);
  a083=7.1868526499999996e+02;
  a084=-1.7523918999999999e+01;
  a085=(a084*a038);
  a083=(a083+a085);
  a085=6.5252556180000001e+03;
  a086=(a085*a040);
  a083=(a083+a086);
  a086=-8.1779472100000003e+03;
  a087=(a086*a042);
  a083=(a083+a087);
  a087=(a082*a055);
  a088=(a083*a087);
  a072=(a072+a088);
  a088=3.2297709999999999e+00;
  a089=1.0991650999999999e+01;
  a090=(a089*a038);
  a088=(a088+a090);
  a090=-2.9369515000000000e+01;
  a091=(a090*a040);
  a088=(a088+a091);
  a091=2.6266324999999998e+01;
  a092=(a091*a042);
  a088=(a088+a092);
  a092=arg[4]? arg[4][0] : 0;
  a093=(a088*a092);
  a094=3.1419312999999999e+01;
  a095=-2.1712130999999999e+02;
  a096=(a095*a038);
  a094=(a094+a096);
  a096=3.9809161499999999e+02;
  a097=(a096*a040);
  a094=(a094+a097);
  a097=-2.0738472999999999e+02;
  a098=(a097*a042);
  a094=(a094+a098);
  a098=casadi_sq(a092);
  a099=(a098*a092);
  a100=(a094*a099);
  a093=(a093+a100);
  a100=-6.3957199500000002e+02;
  a101=1.9119816610000000e+03;
  a102=(a101*a038);
  a100=(a100+a102);
  a102=-2.9751745470000001e+03;
  a103=(a102*a040);
  a100=(a100+a103);
  a103=1.2345741399999999e+03;
  a104=(a103*a042);
  a100=(a100+a104);
  a104=(a099*a098);
  a105=(a100*a104);
  a093=(a093+a105);
  a105=2.4384083030000002e+03;
  a106=-3.1924757900000000e+03;
  a107=(a106*a038);
  a105=(a105+a107);
  a107=3.2756856130000001e+03;
  a108=(a107*a040);
  a105=(a105+a108);
  a108=-3.5469790100000000e+02;
  a109=(a108*a042);
  a105=(a105+a109);
  a098=(a104*a098);
  a109=(a105*a098);
  a093=(a093+a109);
  a072=(a072+a093);
  a093=(a029*a072);
  a109=sin(a054);
  a110=(a093*a109);
  a006=(a006+a110);
  a111=(a068*a056);
  a112=(a057*a056);
  a113=(a073*a112);
  a111=(a111+a113);
  a113=(a112*a057);
  a114=(a078*a113);
  a111=(a111+a114);
  a114=(a113*a057);
  a115=(a083*a114);
  a111=(a111+a115);
  a115=arg[4]? arg[4][1] : 0;
  a088=(a088*a115);
  a116=casadi_sq(a115);
  a117=(a116*a115);
  a094=(a094*a117);
  a088=(a088+a094);
  a094=(a117*a116);
  a100=(a100*a094);
  a088=(a088+a100);
  a116=(a094*a116);
  a105=(a105*a116);
  a088=(a088+a105);
  a111=(a111+a088);
  a088=(a029*a111);
  a105=sin(a056);
  a100=(a088*a105);
  a006=(a006+a100);
  a118=arg[4]? arg[4][3] : 0;
  a119=1.0000000000000000e-03;
  a118=casadi_fmax(a118,a119);
  a006=(a006/a118);
  if (res[0]!=0) res[0][3]=a006;
  a006=(a064*a105);
  a088=(a088*a067);
  a006=(a006+a088);
  a006=(a006/a118);
  a006=(-a006);
  if (res[0]!=0) res[0][4]=a006;
  a006=(a064*a109);
  a119=(a006*a067);
  a093=(a093*a065);
  a119=(a119+a093);
  a119=(a119/a118);
  a119=(-a119);
  if (res[0]!=0) res[0][5]=a119;
  if (res[0]!=0) res[0][6]=a014;
  a119=1000.;
  a120=arg[0]? arg[0][10] : 0;
  a121=(a119*a120);
  if (res[0]!=0) res[0][7]=a121;
  a121=arg[0]? arg[0][11] : 0;
  a122=(a119*a121);
  if (res[0]!=0) res[0][8]=a122;
  if (res[0]!=0) res[0][9]=a014;
  a122=arg[0]? arg[0][1] : 0;
  a123=cos(a122);
  a124=(a023*a123);
  a125=arg[0]? arg[0][2] : 0;
  a126=cos(a125);
  a127=(a124*a126);
  a128=arg[0]? arg[0][15] : 0;
  a129=(a127+a128);
  if (res[0]!=0) res[0][10]=a129;
  a129=sin(a125);
  a130=(a124*a129);
  a131=arg[0]? arg[0][16] : 0;
  a132=(a130+a131);
  if (res[0]!=0) res[0][11]=a132;
  a132=sin(a122);
  a133=(a023*a132);
  a134=(-a133);
  if (res[0]!=0) res[0][12]=a134;
  a134=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][13]=a134;
  a134=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][14]=a134;
  a134=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][15]=a134;
  a134=arg[1]? arg[1][3] : 0;
  if (res[0]!=0) res[0][16]=a134;
  a134=arg[1]? arg[1][4] : 0;
  if (res[0]!=0) res[0][17]=a134;
  a134=arg[1]? arg[1][5] : 0;
  if (res[0]!=0) res[0][18]=a134;
  a134=arg[1]? arg[1][6] : 0;
  if (res[0]!=0) res[0][19]=a134;
  a134=arg[1]? arg[1][7] : 0;
  if (res[0]!=0) res[0][20]=a134;
  a134=arg[1]? arg[1][8] : 0;
  if (res[0]!=0) res[0][21]=a134;
  a134=arg[1]? arg[1][9] : 0;
  if (res[0]!=0) res[0][22]=a134;
  a134=arg[1]? arg[1][10] : 0;
  if (res[0]!=0) res[0][23]=a134;
  a134=arg[1]? arg[1][11] : 0;
  if (res[0]!=0) res[0][24]=a134;
  a134=arg[1]? arg[1][12] : 0;
  if (res[0]!=0) res[0][25]=a134;
  a134=arg[1]? arg[1][13] : 0;
  if (res[0]!=0) res[0][26]=a134;
  a134=arg[1]? arg[1][14] : 0;
  if (res[0]!=0) res[0][27]=a134;
  a134=arg[1]? arg[1][15] : 0;
  if (res[0]!=0) res[0][28]=a134;
  a134=arg[1]? arg[1][16] : 0;
  if (res[0]!=0) res[0][29]=a134;
  if (res[0]!=0) res[0][30]=a023;
  if (res[0]!=0) res[0][31]=a122;
  if (res[0]!=0) res[0][32]=a125;
  if (res[0]!=0) res[0][33]=a000;
  if (res[0]!=0) res[0][34]=a002;
  if (res[0]!=0) res[0][35]=a004;
  if (res[0]!=0) res[0][36]=a054;
  if (res[0]!=0) res[0][37]=a056;
  a004=arg[0]? arg[0][8] : 0;
  if (res[0]!=0) res[0][38]=a004;
  if (res[0]!=0) res[0][39]=a013;
  if (res[0]!=0) res[0][40]=a120;
  if (res[0]!=0) res[0][41]=a121;
  if (res[0]!=0) res[0][42]=a001;
  if (res[0]!=0) res[0][43]=a003;
  if (res[0]!=0) res[0][44]=a005;
  if (res[0]!=0) res[0][45]=a128;
  if (res[0]!=0) res[0][46]=a131;
  if (res[1]!=0) res[1][0]=a026;
  if (res[1]!=0) res[1][1]=a026;
  if (res[1]!=0) res[1][2]=a026;
  if (res[1]!=0) res[1][3]=a026;
  if (res[1]!=0) res[1][4]=a026;
  if (res[1]!=0) res[1][5]=a026;
  a022=(a023*a022);
  a022=(a022+a024);
  a022=(a028*a022);
  a024=6.6666666666666663e-01;
  a027=casadi_sq(a027);
  a027=(a026-a027);
  a024=(a024*a027);
  a024=(a008*a024);
  a025=(a025*a024);
  a022=(a022+a025);
  a022=(a007*a022);
  a025=(a072*a022);
  a024=(a035<=a037);
  a037=(a037<=a035);
  a037=(a024+a037);
  a024=(a024/a037);
  a037=(a036<=a026);
  a036=(a026<=a036);
  a036=(a037+a036);
  a037=(a037/a036);
  a036=(a035<=a034);
  a034=(a034<=a035);
  a034=(a036+a034);
  a036=(a036/a034);
  a034=(a032<=a026);
  a035=(a026<=a032);
  a035=(a034+a035);
  a034=(a034/a035);
  a035=(a026<=a023);
  a027=(a023<=a026);
  a027=(a035+a027);
  a035=(a035/a027);
  a035=(a035/a018);
  a035=(a034*a035);
  a035=(a036*a035);
  a035=(a037*a035);
  a035=(a024*a035);
  a027=(a069*a035);
  a131=(a038+a038);
  a128=(a131*a035);
  a005=(a070*a128);
  a027=(a027+a005);
  a005=(a038*a128);
  a003=(a040*a035);
  a005=(a005+a003);
  a003=(a071*a005);
  a027=(a027+a003);
  a003=(a054*a027);
  a001=(a074*a035);
  a121=(a075*a128);
  a001=(a001+a121);
  a121=(a076*a005);
  a001=(a001+a121);
  a121=(a077*a001);
  a003=(a003+a121);
  a121=(a079*a035);
  a120=(a080*a128);
  a121=(a121+a120);
  a120=(a081*a005);
  a121=(a121+a120);
  a120=(a082*a121);
  a003=(a003+a120);
  a120=(a084*a035);
  a013=(a085*a128);
  a120=(a120+a013);
  a013=(a086*a005);
  a120=(a120+a013);
  a013=(a087*a120);
  a003=(a003+a013);
  a013=(a089*a035);
  a004=(a090*a128);
  a013=(a013+a004);
  a004=(a091*a005);
  a013=(a013+a004);
  a004=(a092*a013);
  a002=(a095*a035);
  a000=(a096*a128);
  a002=(a002+a000);
  a000=(a097*a005);
  a002=(a002+a000);
  a000=(a099*a002);
  a004=(a004+a000);
  a000=(a101*a035);
  a125=(a102*a128);
  a000=(a000+a125);
  a125=(a103*a005);
  a000=(a000+a125);
  a125=(a104*a000);
  a004=(a004+a125);
  a125=(a106*a035);
  a122=(a107*a128);
  a125=(a125+a122);
  a122=(a108*a005);
  a125=(a125+a122);
  a122=(a098*a125);
  a004=(a004+a122);
  a003=(a003+a004);
  a003=(a029*a003);
  a025=(a025+a003);
  a003=(a109*a025);
  a004=(a030*a022);
  a122=(a031*a035);
  a134=(a039*a128);
  a122=(a122+a134);
  a134=(a041*a005);
  a122=(a122+a134);
  a134=(a038*a005);
  a135=(a042*a035);
  a134=(a134+a135);
  a135=(a043*a134);
  a122=(a122+a135);
  a134=(a038*a134);
  a135=(a044*a035);
  a134=(a134+a135);
  a135=(a045*a134);
  a122=(a122+a135);
  a134=(a038*a134);
  a135=(a046*a035);
  a134=(a134+a135);
  a135=(a047*a134);
  a122=(a122+a135);
  a134=(a038*a134);
  a135=(a048*a035);
  a134=(a134+a135);
  a134=(a049*a134);
  a122=(a122+a134);
  a134=(a051*a035);
  a135=(a052*a128);
  a134=(a134+a135);
  a135=(a053*a005);
  a134=(a134+a135);
  a134=(a058*a134);
  a122=(a122+a134);
  a035=(a060*a035);
  a128=(a061*a128);
  a035=(a035+a128);
  a005=(a062*a005);
  a035=(a035+a005);
  a035=(a063*a035);
  a122=(a122+a035);
  a122=(a029*a122);
  a004=(a004+a122);
  a122=(a065*a004);
  a122=(a067*a122);
  a003=(a003-a122);
  a022=(a111*a022);
  a027=(a056*a027);
  a001=(a112*a001);
  a027=(a027+a001);
  a121=(a113*a121);
  a027=(a027+a121);
  a120=(a114*a120);
  a027=(a027+a120);
  a013=(a115*a013);
  a002=(a117*a002);
  a013=(a013+a002);
  a000=(a094*a000);
  a013=(a013+a000);
  a125=(a116*a125);
  a013=(a013+a125);
  a027=(a027+a013);
  a027=(a029*a027);
  a022=(a022+a027);
  a027=(a105*a022);
  a003=(a003+a027);
  a003=(a003/a118);
  if (res[1]!=0) res[1][6]=a003;
  a003=(a054+a054);
  a027=(a054*a003);
  a027=(a027+a055);
  a013=(a073*a027);
  a013=(a068+a013);
  a027=(a055*a027);
  a125=(a077*a003);
  a027=(a027+a125);
  a125=(a078*a027);
  a013=(a013+a125);
  a055=(a055*a027);
  a027=(a082*a003);
  a055=(a055+a027);
  a055=(a083*a055);
  a013=(a013+a055);
  a013=(a029*a013);
  a055=(a109*a013);
  a055=(a055+a093);
  a093=(a050*a003);
  a027=(a058+a058);
  a003=(a027*a003);
  a003=(a059*a003);
  a093=(a093+a003);
  a093=(a029*a093);
  a003=(a065*a093);
  a003=(a003-a006);
  a003=(a067*a003);
  a055=(a055-a003);
  a055=(a055/a118);
  if (res[1]!=0) res[1][7]=a055;
  a055=(a056+a056);
  a003=(a056*a055);
  a003=(a003+a057);
  a073=(a073*a003);
  a068=(a068+a073);
  a003=(a057*a003);
  a073=(a112*a055);
  a003=(a003+a073);
  a078=(a078*a003);
  a068=(a068+a078);
  a057=(a057*a003);
  a003=(a113*a055);
  a057=(a057+a003);
  a083=(a083*a057);
  a068=(a068+a083);
  a068=(a029*a068);
  a083=(a105*a068);
  a083=(a083+a088);
  a050=(a050*a055);
  a027=(a027*a055);
  a059=(a059*a027);
  a050=(a050+a059);
  a050=(a029*a050);
  a059=(a065*a050);
  a059=(a067*a059);
  a027=(a066*a105);
  a059=(a059-a027);
  a083=(a083-a059);
  a083=(a083/a118);
  if (res[1]!=0) res[1][8]=a083;
  a032=(a032/a018);
  a083=(a017<=a016);
  a016=(a016<=a017);
  a016=(a083+a016);
  a083=(a083/a016);
  a016=(a015<=a014);
  a014=(a014<=a015);
  a014=(a016+a014);
  a016=(a016/a014);
  a016=(a012*a016);
  a011=(a011*a016);
  a083=(a083*a011);
  a033=(a033*a083);
  a018=(a018+a018);
  a033=(a033/a018);
  a032=(a032*a033);
  a034=(a034*a032);
  a036=(a036*a034);
  a037=(a037*a036);
  a024=(a024*a037);
  a069=(a069*a024);
  a131=(a131*a024);
  a070=(a070*a131);
  a069=(a069+a070);
  a070=(a038*a131);
  a040=(a040*a024);
  a070=(a070+a040);
  a071=(a071*a070);
  a069=(a069+a071);
  a054=(a054*a069);
  a074=(a074*a024);
  a075=(a075*a131);
  a074=(a074+a075);
  a076=(a076*a070);
  a074=(a074+a076);
  a077=(a077*a074);
  a054=(a054+a077);
  a079=(a079*a024);
  a080=(a080*a131);
  a079=(a079+a080);
  a081=(a081*a070);
  a079=(a079+a081);
  a082=(a082*a079);
  a054=(a054+a082);
  a084=(a084*a024);
  a085=(a085*a131);
  a084=(a084+a085);
  a086=(a086*a070);
  a084=(a084+a086);
  a087=(a087*a084);
  a054=(a054+a087);
  a089=(a089*a024);
  a090=(a090*a131);
  a089=(a089+a090);
  a091=(a091*a070);
  a089=(a089+a091);
  a092=(a092*a089);
  a095=(a095*a024);
  a096=(a096*a131);
  a095=(a095+a096);
  a097=(a097*a070);
  a095=(a095+a097);
  a099=(a099*a095);
  a092=(a092+a099);
  a101=(a101*a024);
  a102=(a102*a131);
  a101=(a101+a102);
  a103=(a103*a070);
  a101=(a101+a103);
  a104=(a104*a101);
  a092=(a092+a104);
  a106=(a106*a024);
  a107=(a107*a131);
  a106=(a106+a107);
  a108=(a108*a070);
  a106=(a106+a108);
  a098=(a098*a106);
  a092=(a092+a098);
  a054=(a054+a092);
  a054=(a029*a054);
  a092=(a021<=a020);
  a020=(a020<=a021);
  a020=(a092+a020);
  a092=(a092/a020);
  a020=3.2559323623598138e+00;
  a010=pow(a010,a020);
  a019=(a019*a010);
  a010=3.4704147145583901e-03;
  a010=(a010*a083);
  a019=(a019*a010);
  a009=(a009*a019);
  a092=(a092*a009);
  a008=(a008*a092);
  a008=(a023*a008);
  a023=(a023*a008);
  a028=(a028*a023);
  a007=(a007*a028);
  a072=(a072*a007);
  a054=(a054-a072);
  a072=(a109*a054);
  a031=(a031*a024);
  a039=(a039*a131);
  a031=(a031+a039);
  a041=(a041*a070);
  a031=(a031+a041);
  a041=(a038*a070);
  a042=(a042*a024);
  a041=(a041+a042);
  a043=(a043*a041);
  a031=(a031+a043);
  a041=(a038*a041);
  a044=(a044*a024);
  a041=(a041+a044);
  a045=(a045*a041);
  a031=(a031+a045);
  a041=(a038*a041);
  a046=(a046*a024);
  a041=(a041+a046);
  a047=(a047*a041);
  a031=(a031+a047);
  a038=(a038*a041);
  a048=(a048*a024);
  a038=(a038+a048);
  a049=(a049*a038);
  a031=(a031+a049);
  a051=(a051*a024);
  a052=(a052*a131);
  a051=(a051+a052);
  a053=(a053*a070);
  a051=(a051+a053);
  a058=(a058*a051);
  a031=(a031+a058);
  a060=(a060*a024);
  a061=(a061*a131);
  a060=(a060+a061);
  a062=(a062*a070);
  a060=(a060+a062);
  a063=(a063*a060);
  a031=(a031+a063);
  a031=(a029*a031);
  a030=(a030*a007);
  a031=(a031-a030);
  a030=(a065*a031);
  a030=(a067*a030);
  a072=(a072-a030);
  a056=(a056*a069);
  a112=(a112*a074);
  a056=(a056+a112);
  a113=(a113*a079);
  a056=(a056+a113);
  a114=(a114*a084);
  a056=(a056+a114);
  a115=(a115*a089);
  a117=(a117*a095);
  a115=(a115+a117);
  a094=(a094*a101);
  a115=(a115+a094);
  a116=(a116*a106);
  a115=(a115+a116);
  a056=(a056+a115);
  a029=(a029*a056);
  a111=(a111*a007);
  a029=(a029-a111);
  a111=(a105*a029);
  a072=(a072+a111);
  a072=(a072/a118);
  if (res[1]!=0) res[1][9]=a072;
  a072=(a105*a004);
  a022=(a067*a022);
  a072=(a072+a022);
  a072=(a072/a118);
  a072=(-a072);
  if (res[1]!=0) res[1][10]=a072;
  a072=(a105*a093);
  a072=(a072/a118);
  a072=(-a072);
  if (res[1]!=0) res[1][11]=a072;
  a072=(a105*a050);
  a064=(a064*a067);
  a072=(a072+a064);
  a068=(a067*a068);
  a068=(a068-a100);
  a072=(a072+a068);
  a072=(a072/a118);
  a072=(-a072);
  if (res[1]!=0) res[1][12]=a072;
  a072=(a105*a031);
  a029=(a067*a029);
  a072=(a072+a029);
  a072=(a072/a118);
  a072=(-a072);
  if (res[1]!=0) res[1][13]=a072;
  a004=(a109*a004);
  a004=(a067*a004);
  a025=(a065*a025);
  a004=(a004+a025);
  a004=(a004/a118);
  a004=(-a004);
  if (res[1]!=0) res[1][14]=a004;
  a093=(a109*a093);
  a093=(a093+a066);
  a093=(a067*a093);
  a013=(a065*a013);
  a013=(a013-a110);
  a093=(a093+a013);
  a093=(a093/a118);
  a093=(-a093);
  if (res[1]!=0) res[1][15]=a093;
  a050=(a109*a050);
  a050=(a067*a050);
  a006=(a006*a105);
  a050=(a050-a006);
  a050=(a050/a118);
  a050=(-a050);
  if (res[1]!=0) res[1][16]=a050;
  a109=(a109*a031);
  a067=(a067*a109);
  a065=(a065*a054);
  a067=(a067+a065);
  a067=(a067/a118);
  a067=(-a067);
  if (res[1]!=0) res[1][17]=a067;
  if (res[1]!=0) res[1][18]=a012;
  if (res[1]!=0) res[1][19]=a119;
  if (res[1]!=0) res[1][20]=a119;
  if (res[1]!=0) res[1][21]=a012;
  a012=(a126*a123);
  if (res[1]!=0) res[1][22]=a012;
  a126=(a126*a133);
  a126=(-a126);
  if (res[1]!=0) res[1][23]=a126;
  a130=(-a130);
  if (res[1]!=0) res[1][24]=a130;
  if (res[1]!=0) res[1][25]=a026;
  a123=(a129*a123);
  if (res[1]!=0) res[1][26]=a123;
  a129=(a129*a133);
  a129=(-a129);
  if (res[1]!=0) res[1][27]=a129;
  if (res[1]!=0) res[1][28]=a127;
  if (res[1]!=0) res[1][29]=a026;
  a132=(-a132);
  if (res[1]!=0) res[1][30]=a132;
  a124=(-a124);
  if (res[1]!=0) res[1][31]=a124;
  if (res[1]!=0) res[1][32]=a026;
  if (res[1]!=0) res[1][33]=a026;
  if (res[1]!=0) res[1][34]=a026;
  if (res[1]!=0) res[1][35]=a026;
  if (res[1]!=0) res[1][36]=a026;
  if (res[1]!=0) res[1][37]=a026;
  if (res[1]!=0) res[1][38]=a026;
  if (res[1]!=0) res[1][39]=a026;
  if (res[1]!=0) res[1][40]=a026;
  if (res[1]!=0) res[1][41]=a026;
  if (res[1]!=0) res[1][42]=a026;
  if (res[1]!=0) res[1][43]=a026;
  if (res[1]!=0) res[1][44]=a026;
  if (res[1]!=0) res[1][45]=a026;
  if (res[1]!=0) res[1][46]=a026;
  if (res[1]!=0) res[1][47]=a026;
  if (res[1]!=0) res[1][48]=a026;
  if (res[1]!=0) res[1][49]=a026;
  if (res[1]!=0) res[1][50]=a026;
  if (res[1]!=0) res[1][51]=a026;
  if (res[1]!=0) res[1][52]=a026;
  if (res[1]!=0) res[1][53]=a026;
  if (res[1]!=0) res[1][54]=a026;
  if (res[1]!=0) res[1][55]=a026;
  if (res[1]!=0) res[1][56]=a026;
  if (res[1]!=0) res[1][57]=a026;
  if (res[1]!=0) res[1][58]=a026;
  if (res[1]!=0) res[1][59]=a026;
  if (res[1]!=0) res[1][60]=a026;
  if (res[1]!=0) res[1][61]=a026;
  if (res[1]!=0) res[1][62]=a026;
  if (res[1]!=0) res[1][63]=a026;
  if (res[1]!=0) res[1][64]=a026;
  if (res[1]!=0) res[1][65]=a026;
  return 0;
}

CASADI_SYMBOL_EXPORT int m130_mhe_cost_y_0_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int m130_mhe_cost_y_0_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int m130_mhe_cost_y_0_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void m130_mhe_cost_y_0_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int m130_mhe_cost_y_0_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void m130_mhe_cost_y_0_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void m130_mhe_cost_y_0_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void m130_mhe_cost_y_0_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int m130_mhe_cost_y_0_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int m130_mhe_cost_y_0_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real m130_mhe_cost_y_0_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* m130_mhe_cost_y_0_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* m130_mhe_cost_y_0_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* m130_mhe_cost_y_0_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* m130_mhe_cost_y_0_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int m130_mhe_cost_y_0_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int m130_mhe_cost_y_0_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
