/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) m130_mhe_cost_y_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {17, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {9, 1, 1};
static const casadi_int casadi_s4[3] = {30, 1, 1};
static const casadi_int casadi_s5[82] = 
  {34, 30, 0, 2, 4, 6, 10, 14,
  18, 19, 20, 21, 22, 26, 30, 32,
  33, 34, 35, 36, 37, 38, 39, 40,
  41, 42, 43, 44, 45, 46, 47, 48,
  49, 20, 29, 21, 30, 22, 31, 17,
  23, 24, 26, 17, 23, 24, 26, 17,
  23, 24, 26, 26, 27, 28, 26, 17,
  18, 19, 32, 17, 18, 19, 33, 17,
  18, 0, 1, 2, 3, 4, 5, 6,
  7, 8, 9, 10, 11, 12, 13, 14,
  15, 16};
static const casadi_int casadi_s6[3] = {30, 0, 1};

/* m130_mhe_cost_y_fun_jac_ut_xt:(i0[17],i1[17],i2[0],i3[],i4[9])->(o0[30],o1[34x30,49nz],o2[30x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a000, a001, a002, a003, a004, a005, a006, a007, a008, a009, a010, a011;
  casadi_real a012, a013, a014, a015, a016, a017, a018, a019, a020, a021, a022, a023;
  casadi_real a024, a025, a026, a027, a028, a029, a030, a031, a032, a033, a034, a035;
  casadi_real a036, a037, a038, a039, a040, a041, a042, a043, a044, a045, a046, a047;
  casadi_real a048, a049, a050, a051, a052, a053, a054, a055, a056, a057, a058, a059;
  casadi_real a060, a061, a062, a063, a064, a065, a066, a067, a068, a069, a070, a071;
  casadi_real a072, a073, a074, a075, a076, a077, a078, a079, a080, a081, a082, a083;
  casadi_real a084, a085, a086, a087, a088, a089, a090, a091, a092, a093, a094, a095;
  casadi_real a096, a097, a098, a099, a100, a101, a102, a103, a104, a105, a106, a107;
  casadi_real a108, a109, a110, a111, a112, a113, a114, a115, a116, a117, a118, a119;
  casadi_real a120, a121, a122, a123, a124, a125, a126, a127, a128, a129, a130, a131;
  casadi_real a132, a133, a134, a135;
  a000=arg[0]? arg[0][3] : 0;
  a001=arg[0]? arg[0][12] : 0;
  a000=(a000+a001);
  if (res[0]!=0) res[0][0]=a000;
  a000=arg[0]? arg[0][4] : 0;
  a001=arg[0]? arg[0][13] : 0;
  a000=(a000+a001);
  if (res[0]!=0) res[0][1]=a000;
  a000=arg[0]? arg[0][5] : 0;
  a001=arg[0]? arg[0][14] : 0;
  a000=(a000+a001);
  if (res[0]!=0) res[0][2]=a000;
  a000=arg[4]? arg[4][4] : 0;
  a001=1.3270000000000001e-02;
  a002=5.0000000000000000e-01;
  a003=1.2250000000000001e+00;
  a004=2.8814999999999998e+02;
  a005=6.4999999999999997e-03;
  a006=100.;
  a007=arg[0]? arg[0][9] : 0;
  a007=(a006*a007);
  a008=arg[4]? arg[4][8] : 0;
  a007=(a007+a008);
  a008=0.;
  a009=casadi_fmax(a007,a008);
  a009=(a005*a009);
  a009=(a004-a009);
  a010=2.1665000000000001e+02;
  a011=casadi_fmax(a009,a010);
  a004=(a011/a004);
  a012=4.2559323623598138e+00;
  a013=pow(a004,a012);
  a013=(a003*a013);
  a014=1.0000000000000000e-10;
  a015=casadi_fmax(a013,a014);
  a015=(a002*a015);
  a016=arg[0]? arg[0][0] : 0;
  a017=(a015*a016);
  a018=(a017*a016);
  a019=1.;
  a020=7.5000000000000000e+00;
  a020=(a016-a020);
  a021=1.5000000000000000e+00;
  a020=(a020/a021);
  a020=tanh(a020);
  a021=(a019+a020);
  a021=(a002*a021);
  a022=(a018*a021);
  a022=(a001*a022);
  a023=6.4465099999999997e-01;
  a024=-6.6772809999999998e+00;
  a025=casadi_fmax(a016,a019);
  a026=4.0187000000000000e+02;
  a011=(a026*a011);
  a011=sqrt(a011);
  a025=(a025/a011);
  a027=casadi_fmin(a025,a019);
  a028=1.0000000000000001e-01;
  a029=casadi_fmax(a027,a028);
  a030=casadi_fmin(a029,a019);
  a031=casadi_fmax(a030,a028);
  a032=(a024*a031);
  a023=(a023+a032);
  a032=5.6985242999999997e+01;
  a033=casadi_sq(a031);
  a034=(a032*a033);
  a023=(a023+a034);
  a034=-2.5248384700000000e+02;
  a035=(a033*a031);
  a036=(a034*a035);
  a023=(a023+a036);
  a036=6.1561736499999995e+02;
  a037=(a035*a031);
  a038=(a036*a037);
  a023=(a023+a038);
  a038=-8.3459076500000003e+02;
  a039=(a037*a031);
  a040=(a038*a039);
  a023=(a023+a040);
  a040=5.8734720100000004e+02;
  a041=(a039*a031);
  a042=(a040*a041);
  a023=(a023+a042);
  a042=-1.6562689000000000e+02;
  a043=(a041*a031);
  a043=(a042*a043);
  a023=(a023+a043);
  a043=5.6522999999999997e-02;
  a044=-9.9855799999999995e-01;
  a045=(a044*a031);
  a043=(a043+a045);
  a045=2.3926500000000002e+00;
  a046=(a045*a033);
  a043=(a043+a046);
  a046=-1.7378279999999999e+00;
  a047=(a046*a035);
  a043=(a043+a047);
  a047=arg[0]? arg[0][6] : 0;
  a048=casadi_sq(a047);
  a049=arg[0]? arg[0][7] : 0;
  a050=casadi_sq(a049);
  a051=(a048+a050);
  a052=(a043*a051);
  a023=(a023+a052);
  a052=-3.0486789999999999e+00;
  a053=5.4473490000000000e+00;
  a054=(a053*a031);
  a052=(a052+a054);
  a054=-9.6709250000000004e+00;
  a055=(a054*a033);
  a052=(a052+a055);
  a055=4.8268709999999997e+00;
  a056=(a055*a035);
  a052=(a052+a056);
  a056=casadi_sq(a051);
  a057=(a052*a056);
  a023=(a023+a057);
  a057=(a022*a023);
  a058=cos(a047);
  a059=(a057*a058);
  a060=cos(a049);
  a061=(a059*a060);
  a000=(a000-a061);
  a061=1.2622483000000001e+01;
  a062=1.1211672000000000e+01;
  a063=(a062*a031);
  a061=(a061+a063);
  a063=-2.8836583999999998e+01;
  a064=(a063*a033);
  a061=(a061+a064);
  a064=2.6861415999999998e+01;
  a065=(a064*a035);
  a061=(a061+a065);
  a065=(a061*a047);
  a066=1.4340211000000000e+01;
  a067=-1.0152808899999999e+02;
  a068=(a067*a031);
  a066=(a066+a068);
  a068=1.4161946200000000e+02;
  a069=(a068*a033);
  a066=(a066+a069);
  a069=-5.3997655999999999e+01;
  a070=(a069*a035);
  a066=(a066+a070);
  a070=(a048*a047);
  a071=(a066*a070);
  a065=(a065+a071);
  a071=-3.1844681800000001e+02;
  a072=7.2491903100000002e+02;
  a073=(a072*a031);
  a071=(a071+a073);
  a073=-1.9602528030000001e+03;
  a074=(a073*a033);
  a071=(a071+a074);
  a074=1.7332038110000001e+03;
  a075=(a074*a035);
  a071=(a071+a075);
  a075=(a070*a048);
  a076=(a071*a075);
  a065=(a065+a076);
  a076=7.1868526499999996e+02;
  a077=-1.7523918999999999e+01;
  a078=(a077*a031);
  a076=(a076+a078);
  a078=6.5252556180000001e+03;
  a079=(a078*a033);
  a076=(a076+a079);
  a079=-8.1779472100000003e+03;
  a080=(a079*a035);
  a076=(a076+a080);
  a080=(a075*a048);
  a081=(a076*a080);
  a065=(a065+a081);
  a081=3.2297709999999999e+00;
  a082=1.0991650999999999e+01;
  a083=(a082*a031);
  a081=(a081+a083);
  a083=-2.9369515000000000e+01;
  a084=(a083*a033);
  a081=(a081+a084);
  a084=2.6266324999999998e+01;
  a085=(a084*a035);
  a081=(a081+a085);
  a085=arg[4]? arg[4][0] : 0;
  a086=(a081*a085);
  a087=3.1419312999999999e+01;
  a088=-2.1712130999999999e+02;
  a089=(a088*a031);
  a087=(a087+a089);
  a089=3.9809161499999999e+02;
  a090=(a089*a033);
  a087=(a087+a090);
  a090=-2.0738472999999999e+02;
  a091=(a090*a035);
  a087=(a087+a091);
  a091=casadi_sq(a085);
  a092=(a091*a085);
  a093=(a087*a092);
  a086=(a086+a093);
  a093=-6.3957199500000002e+02;
  a094=1.9119816610000000e+03;
  a095=(a094*a031);
  a093=(a093+a095);
  a095=-2.9751745470000001e+03;
  a096=(a095*a033);
  a093=(a093+a096);
  a096=1.2345741399999999e+03;
  a097=(a096*a035);
  a093=(a093+a097);
  a097=(a092*a091);
  a098=(a093*a097);
  a086=(a086+a098);
  a098=2.4384083030000002e+03;
  a099=-3.1924757900000000e+03;
  a100=(a099*a031);
  a098=(a098+a100);
  a100=3.2756856130000001e+03;
  a101=(a100*a033);
  a098=(a098+a101);
  a101=-3.5469790100000000e+02;
  a102=(a101*a035);
  a098=(a098+a102);
  a091=(a097*a091);
  a102=(a098*a091);
  a086=(a086+a102);
  a065=(a065+a086);
  a086=(a022*a065);
  a102=sin(a047);
  a103=(a086*a102);
  a000=(a000+a103);
  a104=(a061*a049);
  a105=(a050*a049);
  a106=(a066*a105);
  a104=(a104+a106);
  a106=(a105*a050);
  a107=(a071*a106);
  a104=(a104+a107);
  a107=(a106*a050);
  a108=(a076*a107);
  a104=(a104+a108);
  a108=arg[4]? arg[4][1] : 0;
  a081=(a081*a108);
  a109=casadi_sq(a108);
  a110=(a109*a108);
  a087=(a087*a110);
  a081=(a081+a087);
  a087=(a110*a109);
  a093=(a093*a087);
  a081=(a081+a093);
  a109=(a087*a109);
  a098=(a098*a109);
  a081=(a081+a098);
  a104=(a104+a081);
  a081=(a022*a104);
  a098=sin(a049);
  a093=(a081*a098);
  a000=(a000+a093);
  a111=arg[4]? arg[4][3] : 0;
  a112=1.0000000000000000e-03;
  a111=casadi_fmax(a111,a112);
  a000=(a000/a111);
  if (res[0]!=0) res[0][3]=a000;
  a000=(a057*a098);
  a081=(a081*a060);
  a000=(a000+a081);
  a000=(a000/a111);
  a000=(-a000);
  if (res[0]!=0) res[0][4]=a000;
  a000=(a057*a102);
  a112=(a000*a060);
  a086=(a086*a058);
  a112=(a112+a086);
  a112=(a112/a111);
  a112=(-a112);
  if (res[0]!=0) res[0][5]=a112;
  if (res[0]!=0) res[0][6]=a007;
  a112=1000.;
  a113=arg[0]? arg[0][10] : 0;
  a113=(a112*a113);
  if (res[0]!=0) res[0][7]=a113;
  a113=arg[0]? arg[0][11] : 0;
  a113=(a112*a113);
  if (res[0]!=0) res[0][8]=a113;
  if (res[0]!=0) res[0][9]=a007;
  a113=arg[0]? arg[0][1] : 0;
  a114=cos(a113);
  a115=(a016*a114);
  a116=arg[0]? arg[0][2] : 0;
  a117=cos(a116);
  a118=(a115*a117);
  a119=arg[0]? arg[0][15] : 0;
  a119=(a118+a119);
  if (res[0]!=0) res[0][10]=a119;
  a116=sin(a116);
  a119=(a115*a116);
  a120=arg[0]? arg[0][16] : 0;
  a120=(a119+a120);
  if (res[0]!=0) res[0][11]=a120;
  a113=sin(a113);
  a120=(a016*a113);
  a121=(-a120);
  if (res[0]!=0) res[0][12]=a121;
  a121=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][13]=a121;
  a121=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][14]=a121;
  a121=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][15]=a121;
  a121=arg[1]? arg[1][3] : 0;
  if (res[0]!=0) res[0][16]=a121;
  a121=arg[1]? arg[1][4] : 0;
  if (res[0]!=0) res[0][17]=a121;
  a121=arg[1]? arg[1][5] : 0;
  if (res[0]!=0) res[0][18]=a121;
  a121=arg[1]? arg[1][6] : 0;
  if (res[0]!=0) res[0][19]=a121;
  a121=arg[1]? arg[1][7] : 0;
  if (res[0]!=0) res[0][20]=a121;
  a121=arg[1]? arg[1][8] : 0;
  if (res[0]!=0) res[0][21]=a121;
  a121=arg[1]? arg[1][9] : 0;
  if (res[0]!=0) res[0][22]=a121;
  a121=arg[1]? arg[1][10] : 0;
  if (res[0]!=0) res[0][23]=a121;
  a121=arg[1]? arg[1][11] : 0;
  if (res[0]!=0) res[0][24]=a121;
  a121=arg[1]? arg[1][12] : 0;
  if (res[0]!=0) res[0][25]=a121;
  a121=arg[1]? arg[1][13] : 0;
  if (res[0]!=0) res[0][26]=a121;
  a121=arg[1]? arg[1][14] : 0;
  if (res[0]!=0) res[0][27]=a121;
  a121=arg[1]? arg[1][15] : 0;
  if (res[0]!=0) res[0][28]=a121;
  a121=arg[1]? arg[1][16] : 0;
  if (res[0]!=0) res[0][29]=a121;
  if (res[1]!=0) res[1][0]=a019;
  if (res[1]!=0) res[1][1]=a019;
  if (res[1]!=0) res[1][2]=a019;
  if (res[1]!=0) res[1][3]=a019;
  if (res[1]!=0) res[1][4]=a019;
  if (res[1]!=0) res[1][5]=a019;
  a015=(a016*a015);
  a015=(a015+a017);
  a015=(a021*a015);
  a017=6.6666666666666663e-01;
  a020=casadi_sq(a020);
  a020=(a019-a020);
  a017=(a017*a020);
  a017=(a002*a017);
  a018=(a018*a017);
  a015=(a015+a018);
  a015=(a001*a015);
  a018=(a065*a015);
  a017=(a028<=a030);
  a030=(a030<=a028);
  a030=(a017+a030);
  a017=(a017/a030);
  a030=(a029<=a019);
  a029=(a019<=a029);
  a029=(a030+a029);
  a030=(a030/a029);
  a029=(a028<=a027);
  a027=(a027<=a028);
  a027=(a029+a027);
  a029=(a029/a027);
  a027=(a025<=a019);
  a028=(a019<=a025);
  a028=(a027+a028);
  a027=(a027/a028);
  a028=(a019<=a016);
  a020=(a016<=a019);
  a020=(a028+a020);
  a028=(a028/a020);
  a028=(a028/a011);
  a028=(a027*a028);
  a028=(a029*a028);
  a028=(a030*a028);
  a028=(a017*a028);
  a020=(a062*a028);
  a121=(a031+a031);
  a122=(a121*a028);
  a123=(a063*a122);
  a020=(a020+a123);
  a123=(a031*a122);
  a124=(a033*a028);
  a123=(a123+a124);
  a124=(a064*a123);
  a020=(a020+a124);
  a124=(a047*a020);
  a125=(a067*a028);
  a126=(a068*a122);
  a125=(a125+a126);
  a126=(a069*a123);
  a125=(a125+a126);
  a126=(a070*a125);
  a124=(a124+a126);
  a126=(a072*a028);
  a127=(a073*a122);
  a126=(a126+a127);
  a127=(a074*a123);
  a126=(a126+a127);
  a127=(a075*a126);
  a124=(a124+a127);
  a127=(a077*a028);
  a128=(a078*a122);
  a127=(a127+a128);
  a128=(a079*a123);
  a127=(a127+a128);
  a128=(a080*a127);
  a124=(a124+a128);
  a128=(a082*a028);
  a129=(a083*a122);
  a128=(a128+a129);
  a129=(a084*a123);
  a128=(a128+a129);
  a129=(a085*a128);
  a130=(a088*a028);
  a131=(a089*a122);
  a130=(a130+a131);
  a131=(a090*a123);
  a130=(a130+a131);
  a131=(a092*a130);
  a129=(a129+a131);
  a131=(a094*a028);
  a132=(a095*a122);
  a131=(a131+a132);
  a132=(a096*a123);
  a131=(a131+a132);
  a132=(a097*a131);
  a129=(a129+a132);
  a132=(a099*a028);
  a133=(a100*a122);
  a132=(a132+a133);
  a133=(a101*a123);
  a132=(a132+a133);
  a133=(a091*a132);
  a129=(a129+a133);
  a124=(a124+a129);
  a124=(a022*a124);
  a018=(a018+a124);
  a124=(a102*a018);
  a129=(a023*a015);
  a133=(a024*a028);
  a134=(a032*a122);
  a133=(a133+a134);
  a134=(a034*a123);
  a133=(a133+a134);
  a134=(a031*a123);
  a135=(a035*a028);
  a134=(a134+a135);
  a135=(a036*a134);
  a133=(a133+a135);
  a134=(a031*a134);
  a135=(a037*a028);
  a134=(a134+a135);
  a135=(a038*a134);
  a133=(a133+a135);
  a134=(a031*a134);
  a135=(a039*a028);
  a134=(a134+a135);
  a135=(a040*a134);
  a133=(a133+a135);
  a134=(a031*a134);
  a135=(a041*a028);
  a134=(a134+a135);
  a134=(a042*a134);
  a133=(a133+a134);
  a134=(a044*a028);
  a135=(a045*a122);
  a134=(a134+a135);
  a135=(a046*a123);
  a134=(a134+a135);
  a134=(a051*a134);
  a133=(a133+a134);
  a028=(a053*a028);
  a122=(a054*a122);
  a028=(a028+a122);
  a123=(a055*a123);
  a028=(a028+a123);
  a028=(a056*a028);
  a133=(a133+a028);
  a133=(a022*a133);
  a129=(a129+a133);
  a133=(a058*a129);
  a133=(a060*a133);
  a124=(a124-a133);
  a015=(a104*a015);
  a020=(a049*a020);
  a125=(a105*a125);
  a020=(a020+a125);
  a126=(a106*a126);
  a020=(a020+a126);
  a127=(a107*a127);
  a020=(a020+a127);
  a128=(a108*a128);
  a130=(a110*a130);
  a128=(a128+a130);
  a131=(a087*a131);
  a128=(a128+a131);
  a132=(a109*a132);
  a128=(a128+a132);
  a020=(a020+a128);
  a020=(a022*a020);
  a015=(a015+a020);
  a020=(a098*a015);
  a124=(a124+a020);
  a124=(a124/a111);
  if (res[1]!=0) res[1][6]=a124;
  a124=(a047+a047);
  a020=(a047*a124);
  a020=(a020+a048);
  a128=(a066*a020);
  a128=(a061+a128);
  a020=(a048*a020);
  a132=(a070*a124);
  a020=(a020+a132);
  a132=(a071*a020);
  a128=(a128+a132);
  a048=(a048*a020);
  a020=(a075*a124);
  a048=(a048+a020);
  a048=(a076*a048);
  a128=(a128+a048);
  a128=(a022*a128);
  a048=(a102*a128);
  a048=(a048+a086);
  a086=(a043*a124);
  a020=(a051+a051);
  a124=(a020*a124);
  a124=(a052*a124);
  a086=(a086+a124);
  a086=(a022*a086);
  a124=(a058*a086);
  a124=(a124-a000);
  a124=(a060*a124);
  a048=(a048-a124);
  a048=(a048/a111);
  if (res[1]!=0) res[1][7]=a048;
  a048=(a049+a049);
  a124=(a049*a048);
  a124=(a124+a050);
  a066=(a066*a124);
  a061=(a061+a066);
  a124=(a050*a124);
  a066=(a105*a048);
  a124=(a124+a066);
  a071=(a071*a124);
  a061=(a061+a071);
  a050=(a050*a124);
  a124=(a106*a048);
  a050=(a050+a124);
  a076=(a076*a050);
  a061=(a061+a076);
  a061=(a022*a061);
  a076=(a098*a061);
  a076=(a076+a081);
  a043=(a043*a048);
  a020=(a020*a048);
  a052=(a052*a020);
  a043=(a043+a052);
  a043=(a022*a043);
  a052=(a058*a043);
  a052=(a060*a052);
  a020=(a059*a098);
  a052=(a052-a020);
  a076=(a076-a052);
  a076=(a076/a111);
  if (res[1]!=0) res[1][8]=a076;
  a025=(a025/a011);
  a076=(a010<=a009);
  a009=(a009<=a010);
  a009=(a076+a009);
  a076=(a076/a009);
  a009=(a008<=a007);
  a007=(a007<=a008);
  a007=(a009+a007);
  a009=(a009/a007);
  a009=(a006*a009);
  a005=(a005*a009);
  a076=(a076*a005);
  a026=(a026*a076);
  a011=(a011+a011);
  a026=(a026/a011);
  a025=(a025*a026);
  a027=(a027*a025);
  a029=(a029*a027);
  a030=(a030*a029);
  a017=(a017*a030);
  a062=(a062*a017);
  a121=(a121*a017);
  a063=(a063*a121);
  a062=(a062+a063);
  a063=(a031*a121);
  a033=(a033*a017);
  a063=(a063+a033);
  a064=(a064*a063);
  a062=(a062+a064);
  a047=(a047*a062);
  a067=(a067*a017);
  a068=(a068*a121);
  a067=(a067+a068);
  a069=(a069*a063);
  a067=(a067+a069);
  a070=(a070*a067);
  a047=(a047+a070);
  a072=(a072*a017);
  a073=(a073*a121);
  a072=(a072+a073);
  a074=(a074*a063);
  a072=(a072+a074);
  a075=(a075*a072);
  a047=(a047+a075);
  a077=(a077*a017);
  a078=(a078*a121);
  a077=(a077+a078);
  a079=(a079*a063);
  a077=(a077+a079);
  a080=(a080*a077);
  a047=(a047+a080);
  a082=(a082*a017);
  a083=(a083*a121);
  a082=(a082+a083);
  a084=(a084*a063);
  a082=(a082+a084);
  a085=(a085*a082);
  a088=(a088*a017);
  a089=(a089*a121);
  a088=(a088+a089);
  a090=(a090*a063);
  a088=(a088+a090);
  a092=(a092*a088);
  a085=(a085+a092);
  a094=(a094*a017);
  a095=(a095*a121);
  a094=(a094+a095);
  a096=(a096*a063);
  a094=(a094+a096);
  a097=(a097*a094);
  a085=(a085+a097);
  a099=(a099*a017);
  a100=(a100*a121);
  a099=(a099+a100);
  a101=(a101*a063);
  a099=(a099+a101);
  a091=(a091*a099);
  a085=(a085+a091);
  a047=(a047+a085);
  a047=(a022*a047);
  a085=(a014<=a013);
  a013=(a013<=a014);
  a013=(a085+a013);
  a085=(a085/a013);
  a013=3.2559323623598138e+00;
  a004=pow(a004,a013);
  a012=(a012*a004);
  a004=3.4704147145583901e-03;
  a004=(a004*a076);
  a012=(a012*a004);
  a003=(a003*a012);
  a085=(a085*a003);
  a002=(a002*a085);
  a002=(a016*a002);
  a016=(a016*a002);
  a021=(a021*a016);
  a001=(a001*a021);
  a065=(a065*a001);
  a047=(a047-a065);
  a065=(a102*a047);
  a024=(a024*a017);
  a032=(a032*a121);
  a024=(a024+a032);
  a034=(a034*a063);
  a024=(a024+a034);
  a034=(a031*a063);
  a035=(a035*a017);
  a034=(a034+a035);
  a036=(a036*a034);
  a024=(a024+a036);
  a034=(a031*a034);
  a037=(a037*a017);
  a034=(a034+a037);
  a038=(a038*a034);
  a024=(a024+a038);
  a034=(a031*a034);
  a039=(a039*a017);
  a034=(a034+a039);
  a040=(a040*a034);
  a024=(a024+a040);
  a031=(a031*a034);
  a041=(a041*a017);
  a031=(a031+a041);
  a042=(a042*a031);
  a024=(a024+a042);
  a044=(a044*a017);
  a045=(a045*a121);
  a044=(a044+a045);
  a046=(a046*a063);
  a044=(a044+a046);
  a051=(a051*a044);
  a024=(a024+a051);
  a053=(a053*a017);
  a054=(a054*a121);
  a053=(a053+a054);
  a055=(a055*a063);
  a053=(a053+a055);
  a056=(a056*a053);
  a024=(a024+a056);
  a024=(a022*a024);
  a023=(a023*a001);
  a024=(a024-a023);
  a023=(a058*a024);
  a023=(a060*a023);
  a065=(a065-a023);
  a049=(a049*a062);
  a105=(a105*a067);
  a049=(a049+a105);
  a106=(a106*a072);
  a049=(a049+a106);
  a107=(a107*a077);
  a049=(a049+a107);
  a108=(a108*a082);
  a110=(a110*a088);
  a108=(a108+a110);
  a087=(a087*a094);
  a108=(a108+a087);
  a109=(a109*a099);
  a108=(a108+a109);
  a049=(a049+a108);
  a022=(a022*a049);
  a104=(a104*a001);
  a022=(a022-a104);
  a104=(a098*a022);
  a065=(a065+a104);
  a065=(a065/a111);
  if (res[1]!=0) res[1][9]=a065;
  a065=(a098*a129);
  a015=(a060*a015);
  a065=(a065+a015);
  a065=(a065/a111);
  a065=(-a065);
  if (res[1]!=0) res[1][10]=a065;
  a065=(a098*a086);
  a065=(a065/a111);
  a065=(-a065);
  if (res[1]!=0) res[1][11]=a065;
  a065=(a098*a043);
  a057=(a057*a060);
  a065=(a065+a057);
  a061=(a060*a061);
  a061=(a061-a093);
  a065=(a065+a061);
  a065=(a065/a111);
  a065=(-a065);
  if (res[1]!=0) res[1][12]=a065;
  a065=(a098*a024);
  a022=(a060*a022);
  a065=(a065+a022);
  a065=(a065/a111);
  a065=(-a065);
  if (res[1]!=0) res[1][13]=a065;
  a129=(a102*a129);
  a129=(a060*a129);
  a018=(a058*a018);
  a129=(a129+a018);
  a129=(a129/a111);
  a129=(-a129);
  if (res[1]!=0) res[1][14]=a129;
  a086=(a102*a086);
  a086=(a086+a059);
  a086=(a060*a086);
  a128=(a058*a128);
  a128=(a128-a103);
  a086=(a086+a128);
  a086=(a086/a111);
  a086=(-a086);
  if (res[1]!=0) res[1][15]=a086;
  a043=(a102*a043);
  a043=(a060*a043);
  a000=(a000*a098);
  a043=(a043-a000);
  a043=(a043/a111);
  a043=(-a043);
  if (res[1]!=0) res[1][16]=a043;
  a102=(a102*a024);
  a060=(a060*a102);
  a058=(a058*a047);
  a060=(a060+a058);
  a060=(a060/a111);
  a060=(-a060);
  if (res[1]!=0) res[1][17]=a060;
  if (res[1]!=0) res[1][18]=a006;
  if (res[1]!=0) res[1][19]=a112;
  if (res[1]!=0) res[1][20]=a112;
  if (res[1]!=0) res[1][21]=a006;
  a006=(a117*a114);
  if (res[1]!=0) res[1][22]=a006;
  a117=(a117*a120);
  a117=(-a117);
  if (res[1]!=0) res[1][23]=a117;
  a119=(-a119);
  if (res[1]!=0) res[1][24]=a119;
  if (res[1]!=0) res[1][25]=a019;
  a114=(a116*a114);
  if (res[1]!=0) res[1][26]=a114;
  a116=(a116*a120);
  a116=(-a116);
  if (res[1]!=0) res[1][27]=a116;
  if (res[1]!=0) res[1][28]=a118;
  if (res[1]!=0) res[1][29]=a019;
  a113=(-a113);
  if (res[1]!=0) res[1][30]=a113;
  a115=(-a115);
  if (res[1]!=0) res[1][31]=a115;
  if (res[1]!=0) res[1][32]=a019;
  if (res[1]!=0) res[1][33]=a019;
  if (res[1]!=0) res[1][34]=a019;
  if (res[1]!=0) res[1][35]=a019;
  if (res[1]!=0) res[1][36]=a019;
  if (res[1]!=0) res[1][37]=a019;
  if (res[1]!=0) res[1][38]=a019;
  if (res[1]!=0) res[1][39]=a019;
  if (res[1]!=0) res[1][40]=a019;
  if (res[1]!=0) res[1][41]=a019;
  if (res[1]!=0) res[1][42]=a019;
  if (res[1]!=0) res[1][43]=a019;
  if (res[1]!=0) res[1][44]=a019;
  if (res[1]!=0) res[1][45]=a019;
  if (res[1]!=0) res[1][46]=a019;
  if (res[1]!=0) res[1][47]=a019;
  if (res[1]!=0) res[1][48]=a019;
  return 0;
}

CASADI_SYMBOL_EXPORT int m130_mhe_cost_y_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int m130_mhe_cost_y_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int m130_mhe_cost_y_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void m130_mhe_cost_y_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int m130_mhe_cost_y_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void m130_mhe_cost_y_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void m130_mhe_cost_y_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void m130_mhe_cost_y_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int m130_mhe_cost_y_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int m130_mhe_cost_y_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real m130_mhe_cost_y_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* m130_mhe_cost_y_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* m130_mhe_cost_y_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* m130_mhe_cost_y_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* m130_mhe_cost_y_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int m130_mhe_cost_y_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int m130_mhe_cost_y_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
