/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) m130_mhe_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

static const casadi_int casadi_s0[3] = {17, 1, 1};
static const casadi_int casadi_s1[3] = {9, 1, 1};

/* m130_mhe_expl_ode_fun:(i0[17],i1[17],i2[9])->(o0[17]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41;
  a00=arg[2]? arg[2][4] : 0;
  a01=arg[0]? arg[0][6] : 0;
  a02=cos(a01);
  a03=(a00*a02);
  a04=arg[0]? arg[0][7] : 0;
  a05=cos(a04);
  a03=(a03*a05);
  a05=1.3270000000000001e-02;
  a06=5.0000000000000000e-01;
  a07=1.2250000000000001e+00;
  a08=2.8814999999999998e+02;
  a09=6.4999999999999997e-03;
  a10=100.;
  a11=arg[0]? arg[0][9] : 0;
  a10=(a10*a11);
  a11=arg[2]? arg[2][8] : 0;
  a10=(a10+a11);
  a11=0.;
  a10=casadi_fmax(a10,a11);
  a09=(a09*a10);
  a09=(a08-a09);
  a10=2.1665000000000001e+02;
  a09=casadi_fmax(a09,a10);
  a08=(a09/a08);
  a10=4.2559323623598138e+00;
  a08=pow(a08,a10);
  a07=(a07*a08);
  a08=1.0000000000000000e-10;
  a07=casadi_fmax(a07,a08);
  a07=(a06*a07);
  a08=arg[0]? arg[0][0] : 0;
  a07=(a07*a08);
  a07=(a07*a08);
  a10=1.;
  a11=7.5000000000000000e+00;
  a11=(a08-a11);
  a12=1.5000000000000000e+00;
  a11=(a11/a12);
  a11=tanh(a11);
  a11=(a10+a11);
  a06=(a06*a11);
  a07=(a07*a06);
  a05=(a05*a07);
  a07=6.4465099999999997e-01;
  a06=-6.6772809999999998e+00;
  a08=casadi_fmax(a08,a10);
  a11=4.0187000000000000e+02;
  a11=(a11*a09);
  a11=sqrt(a11);
  a11=(a08/a11);
  a11=casadi_fmin(a11,a10);
  a09=1.0000000000000001e-01;
  a11=casadi_fmax(a11,a09);
  a11=casadi_fmin(a11,a10);
  a11=casadi_fmax(a11,a09);
  a06=(a06*a11);
  a07=(a07+a06);
  a06=5.6985242999999997e+01;
  a09=casadi_sq(a11);
  a06=(a06*a09);
  a07=(a07+a06);
  a06=-2.5248384700000000e+02;
  a10=(a09*a11);
  a06=(a06*a10);
  a07=(a07+a06);
  a06=6.1561736499999995e+02;
  a12=(a10*a11);
  a06=(a06*a12);
  a07=(a07+a06);
  a06=-8.3459076500000003e+02;
  a12=(a12*a11);
  a06=(a06*a12);
  a07=(a07+a06);
  a06=5.8734720100000004e+02;
  a12=(a12*a11);
  a06=(a06*a12);
  a07=(a07+a06);
  a06=-1.6562689000000000e+02;
  a12=(a12*a11);
  a06=(a06*a12);
  a07=(a07+a06);
  a06=5.6522999999999997e-02;
  a12=-9.9855799999999995e-01;
  a12=(a12*a11);
  a06=(a06+a12);
  a12=2.3926500000000002e+00;
  a12=(a12*a09);
  a06=(a06+a12);
  a12=-1.7378279999999999e+00;
  a12=(a12*a10);
  a06=(a06+a12);
  a12=casadi_sq(a01);
  a13=casadi_sq(a04);
  a14=(a12+a13);
  a06=(a06*a14);
  a07=(a07+a06);
  a06=-3.0486789999999999e+00;
  a15=5.4473490000000000e+00;
  a15=(a15*a11);
  a06=(a06+a15);
  a15=-9.6709250000000004e+00;
  a15=(a15*a09);
  a06=(a06+a15);
  a15=4.8268709999999997e+00;
  a15=(a15*a10);
  a06=(a06+a15);
  a14=casadi_sq(a14);
  a06=(a06*a14);
  a07=(a07+a06);
  a07=(a05*a07);
  a03=(a03-a07);
  a07=9.8066499999999994e+00;
  a06=arg[2]? arg[2][3] : 0;
  a14=1.0000000000000000e-03;
  a06=casadi_fmax(a06,a14);
  a15=(a07*a06);
  a16=arg[0]? arg[0][1] : 0;
  a17=sin(a16);
  a15=(a15*a17);
  a03=(a03-a15);
  a03=(a03/a06);
  a15=arg[1]? arg[1][0] : 0;
  a03=(a03+a15);
  if (res[0]!=0) res[0][0]=a03;
  a03=sin(a01);
  a15=arg[0]? arg[0][8] : 0;
  a18=cos(a15);
  a19=(a03*a18);
  a20=sin(a04);
  a02=(a02*a20);
  a15=sin(a15);
  a20=(a02*a15);
  a19=(a19+a20);
  a19=(a00*a19);
  a20=1.2622483000000001e+01;
  a21=1.1211672000000000e+01;
  a21=(a21*a11);
  a20=(a20+a21);
  a21=-2.8836583999999998e+01;
  a21=(a21*a09);
  a20=(a20+a21);
  a21=2.6861415999999998e+01;
  a21=(a21*a10);
  a20=(a20+a21);
  a21=(a20*a01);
  a22=1.4340211000000000e+01;
  a23=-1.0152808899999999e+02;
  a23=(a23*a11);
  a22=(a22+a23);
  a23=1.4161946200000000e+02;
  a23=(a23*a09);
  a22=(a22+a23);
  a23=-5.3997655999999999e+01;
  a23=(a23*a10);
  a22=(a22+a23);
  a23=(a12*a01);
  a24=(a22*a23);
  a21=(a21+a24);
  a24=-3.1844681800000001e+02;
  a25=7.2491903100000002e+02;
  a25=(a25*a11);
  a24=(a24+a25);
  a25=-1.9602528030000001e+03;
  a25=(a25*a09);
  a24=(a24+a25);
  a25=1.7332038110000001e+03;
  a25=(a25*a10);
  a24=(a24+a25);
  a25=(a23*a12);
  a26=(a24*a25);
  a21=(a21+a26);
  a26=7.1868526499999996e+02;
  a27=-1.7523918999999999e+01;
  a27=(a27*a11);
  a26=(a26+a27);
  a27=6.5252556180000001e+03;
  a27=(a27*a09);
  a26=(a26+a27);
  a27=-8.1779472100000003e+03;
  a27=(a27*a10);
  a26=(a26+a27);
  a27=(a25*a12);
  a28=(a26*a27);
  a21=(a21+a28);
  a28=3.2297709999999999e+00;
  a29=1.0991650999999999e+01;
  a29=(a29*a11);
  a28=(a28+a29);
  a29=-2.9369515000000000e+01;
  a29=(a29*a09);
  a28=(a28+a29);
  a29=2.6266324999999998e+01;
  a29=(a29*a10);
  a28=(a28+a29);
  a29=arg[2]? arg[2][0] : 0;
  a30=(a28*a29);
  a31=3.1419312999999999e+01;
  a32=-2.1712130999999999e+02;
  a32=(a32*a11);
  a31=(a31+a32);
  a32=3.9809161499999999e+02;
  a32=(a32*a09);
  a31=(a31+a32);
  a32=-2.0738472999999999e+02;
  a32=(a32*a10);
  a31=(a31+a32);
  a32=casadi_sq(a29);
  a33=(a32*a29);
  a34=(a31*a33);
  a30=(a30+a34);
  a34=-6.3957199500000002e+02;
  a35=1.9119816610000000e+03;
  a35=(a35*a11);
  a34=(a34+a35);
  a35=-2.9751745470000001e+03;
  a35=(a35*a09);
  a34=(a34+a35);
  a35=1.2345741399999999e+03;
  a35=(a35*a10);
  a34=(a34+a35);
  a35=(a33*a32);
  a36=(a34*a35);
  a30=(a30+a36);
  a36=2.4384083030000002e+03;
  a37=-3.1924757900000000e+03;
  a37=(a37*a11);
  a36=(a36+a37);
  a37=3.2756856130000001e+03;
  a37=(a37*a09);
  a36=(a36+a37);
  a37=-3.5469790100000000e+02;
  a37=(a37*a10);
  a36=(a36+a37);
  a32=(a35*a32);
  a37=(a36*a32);
  a30=(a30+a37);
  a21=(a21+a30);
  a21=(a05*a21);
  a30=(a21*a18);
  a19=(a19+a30);
  a20=(a20*a04);
  a30=(a13*a04);
  a22=(a22*a30);
  a20=(a20+a22);
  a22=(a30*a13);
  a24=(a24*a22);
  a20=(a20+a24);
  a24=(a22*a13);
  a26=(a26*a24);
  a20=(a20+a26);
  a26=arg[2]? arg[2][1] : 0;
  a28=(a28*a26);
  a37=casadi_sq(a26);
  a38=(a37*a26);
  a31=(a31*a38);
  a28=(a28+a31);
  a31=(a38*a37);
  a34=(a34*a31);
  a28=(a28+a34);
  a37=(a31*a37);
  a36=(a36*a37);
  a28=(a28+a36);
  a20=(a20+a28);
  a20=(a05*a20);
  a28=(a20*a15);
  a19=(a19+a28);
  a06=(a06*a08);
  a19=(a19/a06);
  a28=cos(a16);
  a07=(a07*a28);
  a07=(a07/a08);
  a19=(a19-a07);
  a07=arg[1]? arg[1][1] : 0;
  a07=(a19+a07);
  if (res[0]!=0) res[0][1]=a07;
  a03=(a03*a15);
  a02=(a02*a18);
  a03=(a03-a02);
  a00=(a00*a03);
  a21=(a21*a15);
  a00=(a00+a21);
  a20=(a20*a18);
  a00=(a00-a20);
  a20=casadi_fabs(a28);
  a21=5.0000000000000003e-02;
  a20=casadi_fmax(a20,a21);
  a06=(a06*a20);
  a00=(a00/a06);
  a06=arg[1]? arg[1][2] : 0;
  a06=(a00+a06);
  if (res[0]!=0) res[0][2]=a06;
  a06=1.3000000000000000e-01;
  a05=(a06*a05);
  a20=5.7295800000000000e+01;
  a21=-2.9927300000000001e-01;
  a03=1.6744400000000001e-01;
  a03=(a03*a11);
  a21=(a21+a03);
  a03=-6.2697000000000003e-01;
  a03=(a03*a09);
  a21=(a21+a03);
  a03=3.9055699999999999e-01;
  a03=(a03*a10);
  a21=(a21+a03);
  a03=-4.7904600000000003e-01;
  a02=1.0339079000000000e+01;
  a02=(a02*a11);
  a03=(a03+a02);
  a02=-1.3302108000000000e+01;
  a02=(a02*a09);
  a03=(a03+a02);
  a02=2.2420140000000002e+00;
  a02=(a02*a10);
  a03=(a03+a02);
  a03=(a03*a12);
  a21=(a21+a03);
  a03=2.3625848999999999e+01;
  a02=-1.1080267600000001e+02;
  a02=(a02*a11);
  a03=(a03+a02);
  a02=1.4602420499999999e+02;
  a02=(a02*a09);
  a03=(a03+a02);
  a02=-4.9198385000000002e+01;
  a02=(a02*a10);
  a03=(a03+a02);
  a03=(a03*a12);
  a03=(a03*a12);
  a21=(a21+a03);
  a21=(a20*a21);
  a03=arg[0]? arg[0][3] : 0;
  a02=(a06*a03);
  a07=2.;
  a07=(a07*a08);
  a02=(a02/a07);
  a21=(a21*a02);
  a02=-1.8529970000000000e+00;
  a36=-4.3393290000000002e+00;
  a36=(a36*a11);
  a02=(a02+a36);
  a36=1.2372914000000000e+01;
  a36=(a36*a09);
  a02=(a02+a36);
  a36=-1.2716224000000000e+01;
  a36=(a36*a10);
  a02=(a02+a36);
  a36=arg[2]? arg[2][2] : 0;
  a02=(a02*a36);
  a21=(a21+a02);
  a21=(a05*a21);
  a02=arg[2]? arg[2][5] : 0;
  a36=1.0000000000000000e-04;
  a02=casadi_fmax(a02,a36);
  a21=(a21/a02);
  a02=arg[1]? arg[1][3] : 0;
  a21=(a21+a02);
  if (res[0]!=0) res[0][3]=a21;
  a21=-9.2393249999999991e+00;
  a02=-5.9737910000000003e+00;
  a02=(a02*a11);
  a21=(a21+a02);
  a02=1.5860243000000001e+01;
  a02=(a02*a09);
  a21=(a21+a02);
  a02=-2.1574051000000001e+01;
  a02=(a02*a10);
  a21=(a21+a02);
  a01=(a21*a01);
  a02=-1.9155148000000001e+01;
  a34=2.1501682400000001e+02;
  a34=(a34*a11);
  a02=(a02+a34);
  a34=-5.1869263699999999e+02;
  a34=(a34*a09);
  a02=(a02+a34);
  a34=3.5413016800000003e+02;
  a34=(a34*a10);
  a02=(a02+a34);
  a23=(a02*a23);
  a01=(a01+a23);
  a23=2.5064975200000001e+02;
  a34=-1.6825658719999999e+03;
  a34=(a34*a11);
  a23=(a23+a34);
  a34=7.2841314869999997e+03;
  a34=(a34*a09);
  a23=(a23+a34);
  a34=-7.3169436640000004e+03;
  a34=(a34*a10);
  a23=(a23+a34);
  a25=(a23*a25);
  a01=(a01+a25);
  a25=2.9906044200000002e+02;
  a34=1.8524295729999999e+03;
  a34=(a34*a11);
  a25=(a25+a34);
  a34=-2.5896146472000000e+04;
  a34=(a34*a09);
  a25=(a25+a34);
  a34=3.1618867445000000e+04;
  a34=(a34*a10);
  a25=(a25+a34);
  a27=(a25*a27);
  a01=(a01+a27);
  a27=-1.1750583000000001e+01;
  a34=-3.9694744000000000e+01;
  a34=(a34*a11);
  a27=(a27+a34);
  a34=1.0621206599999999e+02;
  a34=(a34*a09);
  a27=(a27+a34);
  a34=-9.5130388999999994e+01;
  a34=(a34*a10);
  a27=(a27+a34);
  a29=(a27*a29);
  a34=-1.1208254100000001e+02;
  a39=7.7532038299999999e+02;
  a39=(a39*a11);
  a34=(a34+a39);
  a39=-1.4224302020000000e+03;
  a39=(a39*a09);
  a34=(a34+a39);
  a39=7.4173469899999998e+02;
  a39=(a39*a10);
  a34=(a34+a39);
  a33=(a34*a33);
  a29=(a29+a33);
  a33=2.2885326550000000e+03;
  a39=-6.7312745770000001e+03;
  a39=(a39*a11);
  a33=(a33+a39);
  a39=1.0450846055000000e+04;
  a39=(a39*a09);
  a33=(a33+a39);
  a39=-4.3223483800000004e+03;
  a39=(a39*a10);
  a33=(a33+a39);
  a35=(a33*a35);
  a29=(a29+a35);
  a35=-8.6958707730000006e+03;
  a39=1.0625281698000001e+04;
  a39=(a39*a11);
  a35=(a35+a39);
  a39=-1.0344266148000001e+04;
  a39=(a39*a09);
  a35=(a35+a39);
  a39=6.1871614199999999e+02;
  a39=(a39*a10);
  a35=(a35+a39);
  a32=(a35*a32);
  a29=(a29+a32);
  a01=(a01+a29);
  a29=-2.1924260000000002e+00;
  a32=-2.2064319999999999e+00;
  a32=(a32*a11);
  a29=(a29+a32);
  a32=7.5349209999999998e+00;
  a32=(a32*a09);
  a29=(a29+a32);
  a32=-8.8922419999999995e+00;
  a32=(a32*a10);
  a29=(a29+a32);
  a32=2.3478818000000000e+01;
  a39=5.7307955999999997e+01;
  a39=(a39*a11);
  a32=(a32+a39);
  a39=-1.0870987500000000e+02;
  a39=(a39*a09);
  a32=(a32+a39);
  a39=4.6111668000000002e+01;
  a39=(a39*a10);
  a32=(a32+a39);
  a39=(a32*a12);
  a39=(a29+a39);
  a40=-1.2221128999999999e+01;
  a41=-1.0148882810000000e+03;
  a41=(a41*a11);
  a40=(a40+a41);
  a41=1.7859279300000001e+03;
  a41=(a41*a09);
  a40=(a40+a41);
  a41=-7.6487703399999998e+02;
  a41=(a41*a10);
  a40=(a40+a41);
  a41=(a40*a12);
  a41=(a41*a12);
  a39=(a39+a41);
  a39=(a20*a39);
  a41=arg[0]? arg[0][4] : 0;
  a12=(a06*a41);
  a12=(a12/a07);
  a39=(a39*a12);
  a01=(a01+a39);
  a01=(a05*a01);
  a39=arg[2]? arg[2][6] : 0;
  a39=casadi_fmax(a39,a36);
  a01=(a01/a39);
  a39=arg[1]? arg[1][4] : 0;
  a01=(a01+a39);
  if (res[0]!=0) res[0][4]=a01;
  a27=(a27*a26);
  a34=(a34*a38);
  a27=(a27+a34);
  a33=(a33*a31);
  a27=(a27+a33);
  a35=(a35*a37);
  a27=(a27+a35);
  a21=(a21*a04);
  a02=(a02*a30);
  a21=(a21+a02);
  a23=(a23*a22);
  a21=(a21+a23);
  a25=(a25*a24);
  a21=(a21+a25);
  a27=(a27-a21);
  a32=(a32*a13);
  a29=(a29+a32);
  a40=(a40*a13);
  a40=(a40*a13);
  a29=(a29+a40);
  a20=(a20*a29);
  a29=arg[0]? arg[0][5] : 0;
  a06=(a06*a29);
  a06=(a06/a07);
  a20=(a20*a06);
  a27=(a27+a20);
  a05=(a05*a27);
  a27=arg[2]? arg[2][7] : 0;
  a27=casadi_fmax(a27,a36);
  a05=(a05/a27);
  a27=arg[1]? arg[1][5] : 0;
  a05=(a05+a27);
  if (res[0]!=0) res[0][5]=a05;
  a05=(a19*a18);
  a05=(a41-a05);
  a00=(a00*a28);
  a27=(a00*a15);
  a05=(a05-a27);
  a27=arg[1]? arg[1][6] : 0;
  a05=(a05+a27);
  if (res[0]!=0) res[0][6]=a05;
  a00=(a00*a18);
  a19=(a19*a15);
  a19=(a29+a19);
  a00=(a00-a19);
  a19=arg[1]? arg[1][7] : 0;
  a00=(a00+a19);
  if (res[0]!=0) res[0][7]=a00;
  a41=(a41*a15);
  a29=(a29*a18);
  a41=(a41+a29);
  a29=1.3999999999999999e+00;
  a16=casadi_fmin(a16,a29);
  a29=-1.3999999999999999e+00;
  a16=casadi_fmax(a16,a29);
  a16=tan(a16);
  a41=(a41*a16);
  a03=(a03+a41);
  a41=arg[1]? arg[1][8] : 0;
  a03=(a03+a41);
  if (res[0]!=0) res[0][8]=a03;
  a03=1.0000000000000000e-02;
  a17=(a08*a17);
  a03=(a03*a17);
  a17=arg[1]? arg[1][9] : 0;
  a03=(a03+a17);
  if (res[0]!=0) res[0][9]=a03;
  a08=(a08*a28);
  a28=arg[0]? arg[0][2] : 0;
  a03=cos(a28);
  a03=(a08*a03);
  a03=(a14*a03);
  a17=arg[1]? arg[1][10] : 0;
  a03=(a03+a17);
  if (res[0]!=0) res[0][10]=a03;
  a28=sin(a28);
  a08=(a08*a28);
  a14=(a14*a08);
  a08=arg[1]? arg[1][11] : 0;
  a14=(a14+a08);
  if (res[0]!=0) res[0][11]=a14;
  a14=arg[1]? arg[1][12] : 0;
  if (res[0]!=0) res[0][12]=a14;
  a14=arg[1]? arg[1][13] : 0;
  if (res[0]!=0) res[0][13]=a14;
  a14=arg[1]? arg[1][14] : 0;
  if (res[0]!=0) res[0][14]=a14;
  a14=arg[1]? arg[1][15] : 0;
  if (res[0]!=0) res[0][15]=a14;
  a14=arg[1]? arg[1][16] : 0;
  if (res[0]!=0) res[0][16]=a14;
  return 0;
}

CASADI_SYMBOL_EXPORT int m130_mhe_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int m130_mhe_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int m130_mhe_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void m130_mhe_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int m130_mhe_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void m130_mhe_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void m130_mhe_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void m130_mhe_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int m130_mhe_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int m130_mhe_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real m130_mhe_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* m130_mhe_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* m130_mhe_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* m130_mhe_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* m130_mhe_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int m130_mhe_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int m130_mhe_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
