#!/bin/bash
# ======================================================================
#  Cross-compile libm130_solvers.a for arm64-v8a (Android)
#
#  This builds the acados-generated MPC+MHE solver C sources from
#  c_generated_code/ into a static library for the Android app.
#
#  Prerequisites:
#    - Android NDK 27+ installed (ANDROID_NDK_HOME or default path)
#    - c_generated_code/ generated by m130_ocp_setup.py (any N)
#    - acados_arm64/include/ headers present
#
#  Usage:
#    ./scripts/build_m130_solvers_arm64.sh
#
#  Output:
#    AndroidApp/app/src/main/cpp/acados_arm64/lib/libm130_solvers.a
# ======================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# ---- Find NDK ----
if [ -n "${ANDROID_NDK_HOME:-}" ]; then
    NDK="$ANDROID_NDK_HOME"
elif [ -d "$HOME/Android/Sdk/ndk" ]; then
    NDK="$(ls -d "$HOME/Android/Sdk/ndk"/*/ 2>/dev/null | sort -V | tail -1)"
    NDK="${NDK%/}"
else
    echo "ERROR: Cannot find Android NDK. Set ANDROID_NDK_HOME." >&2
    exit 1
fi

CC="$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android26-clang"
AR="$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"

if [ ! -x "$CC" ]; then
    echo "ERROR: Compiler not found: $CC" >&2
    exit 1
fi

# ---- Paths ----
SOLVER_ROOT="$REPO_ROOT/c_generated_code"
ACADOS_INC="$REPO_ROOT/AndroidApp/app/src/main/cpp/acados_arm64/include"
OUT_DIR="$REPO_ROOT/AndroidApp/app/src/main/cpp/acados_arm64/lib"
BUILD_DIR="/tmp/m130_arm64_build_$$"

# ---- Read N from headers (must match m130_ocp_setup.py) ----
N_LINE=$(grep '#define M130_ROCKET_N ' "$SOLVER_ROOT/acados_solver_m130_rocket.h" || true)
if [ -z "$N_LINE" ]; then
    echo "ERROR: M130_ROCKET_N not found in $SOLVER_ROOT/acados_solver_m130_rocket.h" >&2
    echo "  Regenerate c_generated_code/ by running m130_ocp_setup.py or the standalone sim first." >&2
    exit 1
fi
MPC_N=$(echo "$N_LINE" | awk '{print $3}')

CFLAGS="-O2 -DNDEBUG -fPIC -w \
  -I${SOLVER_ROOT} \
  -I${SOLVER_ROOT}/m130_rocket_model \
  -I${SOLVER_ROOT}/m130_mhe_model \
  -I${SOLVER_ROOT}/m130_mhe_cost \
  -I${ACADOS_INC} \
  -I${ACADOS_INC}/acados \
  -I${ACADOS_INC}/blasfeo/include \
  -I${ACADOS_INC}/hpipm/include"

# ---- Solver sources (must match rocket_mpc/CMakeLists.txt) ----
SOURCES=(
  "$SOLVER_ROOT/acados_solver_m130_rocket.c"
  "$SOLVER_ROOT/acados_solver_m130_mhe.c"
  "$SOLVER_ROOT/acados_sim_solver_m130_rocket.c"
  "$SOLVER_ROOT/acados_sim_solver_m130_mhe.c"
  "$SOLVER_ROOT/m130_rocket_model/m130_rocket_expl_ode_fun.c"
  "$SOLVER_ROOT/m130_rocket_model/m130_rocket_expl_vde_adj.c"
  "$SOLVER_ROOT/m130_rocket_model/m130_rocket_expl_vde_forw.c"
  "$SOLVER_ROOT/m130_mhe_model/m130_mhe_expl_ode_fun.c"
  "$SOLVER_ROOT/m130_mhe_model/m130_mhe_expl_vde_adj.c"
  "$SOLVER_ROOT/m130_mhe_model/m130_mhe_expl_vde_forw.c"
  "$SOLVER_ROOT/m130_mhe_cost/m130_mhe_cost_y_0_fun.c"
  "$SOLVER_ROOT/m130_mhe_cost/m130_mhe_cost_y_0_fun_jac_ut_xt.c"
  "$SOLVER_ROOT/m130_mhe_cost/m130_mhe_cost_y_0_hess.c"
  "$SOLVER_ROOT/m130_mhe_cost/m130_mhe_cost_y_fun.c"
  "$SOLVER_ROOT/m130_mhe_cost/m130_mhe_cost_y_fun_jac_ut_xt.c"
  "$SOLVER_ROOT/m130_mhe_cost/m130_mhe_cost_y_hess.c"
)

mkdir -p "$BUILD_DIR" "$OUT_DIR"

echo "Building libm130_solvers.a for arm64 (N=${MPC_N})..."
echo "  NDK: $NDK"
echo "  CC:  $CC"
echo "  Sources: ${#SOURCES[@]} files"

OBJS=()
for src in "${SOURCES[@]}"; do
    obj="$BUILD_DIR/$(basename "${src%.c}.o")"
    $CC $CFLAGS -c "$src" -o "$obj"
    OBJS+=("$obj")
done

rm -f "$OUT_DIR/libm130_solvers.a"  # ensure clean archive (ar rcs appends if file exists)
$AR rcs "$OUT_DIR/libm130_solvers.a" "${OBJS[@]}"

rm -rf "$BUILD_DIR"

SIZE=$(stat -c%s "$OUT_DIR/libm130_solvers.a")
echo "Done: $OUT_DIR/libm130_solvers.a ($SIZE bytes)"

# ---- Sync headers to Android m130_mpc/ ----
ANDROID_HDR="$REPO_ROOT/AndroidApp/app/src/main/cpp/m130_mpc"
for h in acados_solver_m130_rocket.h acados_solver_m130_mhe.h \
         acados_sim_solver_m130_rocket.h acados_sim_solver_m130_mhe.h; do
    cp "$SOLVER_ROOT/$h" "$ANDROID_HDR/$h"
done
echo "Headers synced to $ANDROID_HDR/"
