/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) m130_mhe_cost_y_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {17, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {9, 1, 1};
static const casadi_int casadi_s4[3] = {30, 1, 1};

/* m130_mhe_cost_y_fun:(i0[17],i1[17],i2[0],i3[],i4[9])->(o0[30]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25;
  a00=arg[0]? arg[0][3] : 0;
  a01=arg[0]? arg[0][12] : 0;
  a00=(a00+a01);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][4] : 0;
  a01=arg[0]? arg[0][13] : 0;
  a00=(a00+a01);
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[0]? arg[0][5] : 0;
  a01=arg[0]? arg[0][14] : 0;
  a00=(a00+a01);
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[4]? arg[4][4] : 0;
  a01=1.3270000000000001e-02;
  a02=5.0000000000000000e-01;
  a03=1.2250000000000001e+00;
  a04=2.8814999999999998e+02;
  a05=6.4999999999999997e-03;
  a06=100.;
  a07=arg[0]? arg[0][9] : 0;
  a06=(a06*a07);
  a07=arg[4]? arg[4][8] : 0;
  a06=(a06+a07);
  a07=0.;
  a07=casadi_fmax(a06,a07);
  a05=(a05*a07);
  a05=(a04-a05);
  a07=2.1665000000000001e+02;
  a05=casadi_fmax(a05,a07);
  a04=(a05/a04);
  a07=4.2559323623598138e+00;
  a04=pow(a04,a07);
  a03=(a03*a04);
  a04=1.0000000000000000e-10;
  a03=casadi_fmax(a03,a04);
  a03=(a02*a03);
  a04=arg[0]? arg[0][0] : 0;
  a03=(a03*a04);
  a03=(a03*a04);
  a07=1.;
  a08=7.5000000000000000e+00;
  a08=(a04-a08);
  a09=1.5000000000000000e+00;
  a08=(a08/a09);
  a08=tanh(a08);
  a08=(a07+a08);
  a02=(a02*a08);
  a03=(a03*a02);
  a01=(a01*a03);
  a03=6.4465099999999997e-01;
  a02=-6.6772809999999998e+00;
  a08=casadi_fmax(a04,a07);
  a09=4.0187000000000000e+02;
  a09=(a09*a05);
  a09=sqrt(a09);
  a08=(a08/a09);
  a08=casadi_fmin(a08,a07);
  a09=1.0000000000000001e-01;
  a08=casadi_fmax(a08,a09);
  a08=casadi_fmin(a08,a07);
  a08=casadi_fmax(a08,a09);
  a02=(a02*a08);
  a03=(a03+a02);
  a02=5.6985242999999997e+01;
  a09=casadi_sq(a08);
  a02=(a02*a09);
  a03=(a03+a02);
  a02=-2.5248384700000000e+02;
  a07=(a09*a08);
  a02=(a02*a07);
  a03=(a03+a02);
  a02=6.1561736499999995e+02;
  a05=(a07*a08);
  a02=(a02*a05);
  a03=(a03+a02);
  a02=-8.3459076500000003e+02;
  a05=(a05*a08);
  a02=(a02*a05);
  a03=(a03+a02);
  a02=5.8734720100000004e+02;
  a05=(a05*a08);
  a02=(a02*a05);
  a03=(a03+a02);
  a02=-1.6562689000000000e+02;
  a05=(a05*a08);
  a02=(a02*a05);
  a03=(a03+a02);
  a02=5.6522999999999997e-02;
  a05=-9.9855799999999995e-01;
  a05=(a05*a08);
  a02=(a02+a05);
  a05=2.3926500000000002e+00;
  a05=(a05*a09);
  a02=(a02+a05);
  a05=-1.7378279999999999e+00;
  a05=(a05*a07);
  a02=(a02+a05);
  a05=arg[0]? arg[0][6] : 0;
  a10=casadi_sq(a05);
  a11=arg[0]? arg[0][7] : 0;
  a12=casadi_sq(a11);
  a13=(a10+a12);
  a02=(a02*a13);
  a03=(a03+a02);
  a02=-3.0486789999999999e+00;
  a14=5.4473490000000000e+00;
  a14=(a14*a08);
  a02=(a02+a14);
  a14=-9.6709250000000004e+00;
  a14=(a14*a09);
  a02=(a02+a14);
  a14=4.8268709999999997e+00;
  a14=(a14*a07);
  a02=(a02+a14);
  a13=casadi_sq(a13);
  a02=(a02*a13);
  a03=(a03+a02);
  a03=(a01*a03);
  a02=cos(a05);
  a13=(a03*a02);
  a14=cos(a11);
  a13=(a13*a14);
  a00=(a00-a13);
  a13=1.2622483000000001e+01;
  a15=1.1211672000000000e+01;
  a15=(a15*a08);
  a13=(a13+a15);
  a15=-2.8836583999999998e+01;
  a15=(a15*a09);
  a13=(a13+a15);
  a15=2.6861415999999998e+01;
  a15=(a15*a07);
  a13=(a13+a15);
  a15=(a13*a05);
  a16=1.4340211000000000e+01;
  a17=-1.0152808899999999e+02;
  a17=(a17*a08);
  a16=(a16+a17);
  a17=1.4161946200000000e+02;
  a17=(a17*a09);
  a16=(a16+a17);
  a17=-5.3997655999999999e+01;
  a17=(a17*a07);
  a16=(a16+a17);
  a17=(a10*a05);
  a18=(a16*a17);
  a15=(a15+a18);
  a18=-3.1844681800000001e+02;
  a19=7.2491903100000002e+02;
  a19=(a19*a08);
  a18=(a18+a19);
  a19=-1.9602528030000001e+03;
  a19=(a19*a09);
  a18=(a18+a19);
  a19=1.7332038110000001e+03;
  a19=(a19*a07);
  a18=(a18+a19);
  a17=(a17*a10);
  a19=(a18*a17);
  a15=(a15+a19);
  a19=7.1868526499999996e+02;
  a20=-1.7523918999999999e+01;
  a20=(a20*a08);
  a19=(a19+a20);
  a20=6.5252556180000001e+03;
  a20=(a20*a09);
  a19=(a19+a20);
  a20=-8.1779472100000003e+03;
  a20=(a20*a07);
  a19=(a19+a20);
  a17=(a17*a10);
  a17=(a19*a17);
  a15=(a15+a17);
  a17=3.2297709999999999e+00;
  a10=1.0991650999999999e+01;
  a10=(a10*a08);
  a17=(a17+a10);
  a10=-2.9369515000000000e+01;
  a10=(a10*a09);
  a17=(a17+a10);
  a10=2.6266324999999998e+01;
  a10=(a10*a07);
  a17=(a17+a10);
  a10=arg[4]? arg[4][0] : 0;
  a20=(a17*a10);
  a21=3.1419312999999999e+01;
  a22=-2.1712130999999999e+02;
  a22=(a22*a08);
  a21=(a21+a22);
  a22=3.9809161499999999e+02;
  a22=(a22*a09);
  a21=(a21+a22);
  a22=-2.0738472999999999e+02;
  a22=(a22*a07);
  a21=(a21+a22);
  a22=casadi_sq(a10);
  a10=(a22*a10);
  a23=(a21*a10);
  a20=(a20+a23);
  a23=-6.3957199500000002e+02;
  a24=1.9119816610000000e+03;
  a24=(a24*a08);
  a23=(a23+a24);
  a24=-2.9751745470000001e+03;
  a24=(a24*a09);
  a23=(a23+a24);
  a24=1.2345741399999999e+03;
  a24=(a24*a07);
  a23=(a23+a24);
  a10=(a10*a22);
  a24=(a23*a10);
  a20=(a20+a24);
  a24=2.4384083030000002e+03;
  a25=-3.1924757900000000e+03;
  a25=(a25*a08);
  a24=(a24+a25);
  a25=3.2756856130000001e+03;
  a25=(a25*a09);
  a24=(a24+a25);
  a25=-3.5469790100000000e+02;
  a25=(a25*a07);
  a24=(a24+a25);
  a10=(a10*a22);
  a10=(a24*a10);
  a20=(a20+a10);
  a15=(a15+a20);
  a15=(a01*a15);
  a05=sin(a05);
  a20=(a15*a05);
  a00=(a00+a20);
  a13=(a13*a11);
  a20=(a12*a11);
  a16=(a16*a20);
  a13=(a13+a16);
  a20=(a20*a12);
  a18=(a18*a20);
  a13=(a13+a18);
  a20=(a20*a12);
  a19=(a19*a20);
  a13=(a13+a19);
  a19=arg[4]? arg[4][1] : 0;
  a17=(a17*a19);
  a20=casadi_sq(a19);
  a19=(a20*a19);
  a21=(a21*a19);
  a17=(a17+a21);
  a19=(a19*a20);
  a23=(a23*a19);
  a17=(a17+a23);
  a19=(a19*a20);
  a24=(a24*a19);
  a17=(a17+a24);
  a13=(a13+a17);
  a01=(a01*a13);
  a11=sin(a11);
  a13=(a01*a11);
  a00=(a00+a13);
  a13=arg[4]? arg[4][3] : 0;
  a17=1.0000000000000000e-03;
  a13=casadi_fmax(a13,a17);
  a00=(a00/a13);
  if (res[0]!=0) res[0][3]=a00;
  a11=(a03*a11);
  a01=(a01*a14);
  a11=(a11+a01);
  a11=(a11/a13);
  a11=(-a11);
  if (res[0]!=0) res[0][4]=a11;
  a03=(a03*a05);
  a03=(a03*a14);
  a15=(a15*a02);
  a03=(a03+a15);
  a03=(a03/a13);
  a03=(-a03);
  if (res[0]!=0) res[0][5]=a03;
  if (res[0]!=0) res[0][6]=a06;
  a03=1000.;
  a13=arg[0]? arg[0][10] : 0;
  a13=(a03*a13);
  if (res[0]!=0) res[0][7]=a13;
  a13=arg[0]? arg[0][11] : 0;
  a03=(a03*a13);
  if (res[0]!=0) res[0][8]=a03;
  if (res[0]!=0) res[0][9]=a06;
  a06=arg[0]? arg[0][1] : 0;
  a03=cos(a06);
  a03=(a04*a03);
  a13=arg[0]? arg[0][2] : 0;
  a15=cos(a13);
  a15=(a03*a15);
  a02=arg[0]? arg[0][15] : 0;
  a15=(a15+a02);
  if (res[0]!=0) res[0][10]=a15;
  a13=sin(a13);
  a03=(a03*a13);
  a13=arg[0]? arg[0][16] : 0;
  a03=(a03+a13);
  if (res[0]!=0) res[0][11]=a03;
  a06=sin(a06);
  a04=(a04*a06);
  a04=(-a04);
  if (res[0]!=0) res[0][12]=a04;
  a04=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][13]=a04;
  a04=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][14]=a04;
  a04=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][15]=a04;
  a04=arg[1]? arg[1][3] : 0;
  if (res[0]!=0) res[0][16]=a04;
  a04=arg[1]? arg[1][4] : 0;
  if (res[0]!=0) res[0][17]=a04;
  a04=arg[1]? arg[1][5] : 0;
  if (res[0]!=0) res[0][18]=a04;
  a04=arg[1]? arg[1][6] : 0;
  if (res[0]!=0) res[0][19]=a04;
  a04=arg[1]? arg[1][7] : 0;
  if (res[0]!=0) res[0][20]=a04;
  a04=arg[1]? arg[1][8] : 0;
  if (res[0]!=0) res[0][21]=a04;
  a04=arg[1]? arg[1][9] : 0;
  if (res[0]!=0) res[0][22]=a04;
  a04=arg[1]? arg[1][10] : 0;
  if (res[0]!=0) res[0][23]=a04;
  a04=arg[1]? arg[1][11] : 0;
  if (res[0]!=0) res[0][24]=a04;
  a04=arg[1]? arg[1][12] : 0;
  if (res[0]!=0) res[0][25]=a04;
  a04=arg[1]? arg[1][13] : 0;
  if (res[0]!=0) res[0][26]=a04;
  a04=arg[1]? arg[1][14] : 0;
  if (res[0]!=0) res[0][27]=a04;
  a04=arg[1]? arg[1][15] : 0;
  if (res[0]!=0) res[0][28]=a04;
  a04=arg[1]? arg[1][16] : 0;
  if (res[0]!=0) res[0][29]=a04;
  return 0;
}

CASADI_SYMBOL_EXPORT int m130_mhe_cost_y_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int m130_mhe_cost_y_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int m130_mhe_cost_y_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void m130_mhe_cost_y_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int m130_mhe_cost_y_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void m130_mhe_cost_y_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void m130_mhe_cost_y_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void m130_mhe_cost_y_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int m130_mhe_cost_y_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int m130_mhe_cost_y_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real m130_mhe_cost_y_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* m130_mhe_cost_y_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* m130_mhe_cost_y_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* m130_mhe_cost_y_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* m130_mhe_cost_y_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int m130_mhe_cost_y_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int m130_mhe_cost_y_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
