/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) m130_rocket_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

static const casadi_int casadi_s0[3] = {18, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {2, 1, 1};

/* m130_rocket_expl_ode_fun:(i0[18],i1[3],i2[2])->(o0[18]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46;
  a00=arg[2]? arg[2][1] : 0;
  a01=arg[0]? arg[0][6] : 0;
  a02=cos(a01);
  a03=(a00*a02);
  a04=arg[0]? arg[0][7] : 0;
  a05=cos(a04);
  a03=(a03*a05);
  a05=1.3270000000000001e-02;
  a06=5.0000000000000000e-01;
  a07=1.2250000000000001e+00;
  a08=2.8814999999999998e+02;
  a09=6.4999999999999997e-03;
  a10=100.;
  a11=arg[0]? arg[0][9] : 0;
  a10=(a10*a11);
  a11=1200.;
  a10=(a10+a11);
  a11=0.;
  a10=casadi_fmax(a10,a11);
  a09=(a09*a10);
  a09=(a08-a09);
  a10=2.1665000000000001e+02;
  a09=casadi_fmax(a09,a10);
  a08=(a09/a08);
  a10=4.2559323623598138e+00;
  a08=pow(a08,a10);
  a07=(a07*a08);
  a08=1.0000000000000000e-10;
  a07=casadi_fmax(a07,a08);
  a07=(a06*a07);
  a08=arg[0]? arg[0][0] : 0;
  a07=(a07*a08);
  a07=(a07*a08);
  a10=1.;
  a12=7.5000000000000000e+00;
  a12=(a08-a12);
  a13=1.5000000000000000e+00;
  a12=(a12/a13);
  a12=tanh(a12);
  a12=(a10+a12);
  a06=(a06*a12);
  a07=(a07*a06);
  a05=(a05*a07);
  a07=6.4465099999999997e-01;
  a06=-6.6772809999999998e+00;
  a12=4.0187000000000000e+02;
  a12=(a12*a09);
  a12=sqrt(a12);
  a12=(a08/a12);
  a09=1.0000000000000001e-01;
  a12=casadi_fmax(a12,a09);
  a12=casadi_fmin(a12,a10);
  a12=casadi_fmin(a12,a10);
  a12=casadi_fmax(a12,a09);
  a06=(a06*a12);
  a07=(a07+a06);
  a06=5.6985242999999997e+01;
  a09=casadi_sq(a12);
  a06=(a06*a09);
  a07=(a07+a06);
  a06=-2.5248384700000000e+02;
  a13=(a09*a12);
  a06=(a06*a13);
  a07=(a07+a06);
  a06=6.1561736499999995e+02;
  a14=(a13*a12);
  a06=(a06*a14);
  a07=(a07+a06);
  a06=-8.3459076500000003e+02;
  a14=(a14*a12);
  a06=(a06*a14);
  a07=(a07+a06);
  a06=5.8734720100000004e+02;
  a14=(a14*a12);
  a06=(a06*a14);
  a07=(a07+a06);
  a06=-1.6562689000000000e+02;
  a14=(a14*a12);
  a06=(a06*a14);
  a07=(a07+a06);
  a06=5.6522999999999997e-02;
  a14=-9.9855799999999995e-01;
  a14=(a14*a12);
  a06=(a06+a14);
  a14=2.3926500000000002e+00;
  a14=(a14*a09);
  a06=(a06+a14);
  a14=-1.7378279999999999e+00;
  a14=(a14*a13);
  a06=(a06+a14);
  a14=casadi_sq(a01);
  a15=casadi_sq(a04);
  a16=(a14+a15);
  a06=(a06*a16);
  a07=(a07+a06);
  a06=-3.0486789999999999e+00;
  a17=5.4473490000000000e+00;
  a17=(a17*a12);
  a06=(a06+a17);
  a17=-9.6709250000000004e+00;
  a17=(a17*a09);
  a06=(a06+a17);
  a17=4.8268709999999997e+00;
  a17=(a17*a13);
  a06=(a06+a17);
  a16=casadi_sq(a16);
  a06=(a06*a16);
  a07=(a07+a06);
  a07=(a05*a07);
  a03=(a03-a07);
  a07=9.8066499999999994e+00;
  a06=arg[2]? arg[2][0] : 0;
  a16=(a07*a06);
  a17=arg[0]? arg[0][1] : 0;
  a18=sin(a17);
  a16=(a16*a18);
  a03=(a03-a16);
  a03=(a03/a06);
  if (res[0]!=0) res[0][0]=a03;
  a03=sin(a01);
  a16=arg[0]? arg[0][8] : 0;
  a19=cos(a16);
  a20=(a03*a19);
  a21=sin(a04);
  a02=(a02*a21);
  a16=sin(a16);
  a21=(a02*a16);
  a20=(a20+a21);
  a20=(a00*a20);
  a21=1.2622483000000001e+01;
  a22=1.1211672000000000e+01;
  a22=(a22*a12);
  a21=(a21+a22);
  a22=-2.8836583999999998e+01;
  a22=(a22*a09);
  a21=(a21+a22);
  a22=2.6861415999999998e+01;
  a22=(a22*a13);
  a21=(a21+a22);
  a22=(a21*a01);
  a23=1.4340211000000000e+01;
  a24=-1.0152808899999999e+02;
  a24=(a24*a12);
  a23=(a23+a24);
  a24=1.4161946200000000e+02;
  a24=(a24*a09);
  a23=(a23+a24);
  a24=-5.3997655999999999e+01;
  a24=(a24*a13);
  a23=(a23+a24);
  a24=(a14*a01);
  a25=(a23*a24);
  a22=(a22+a25);
  a25=-3.1844681800000001e+02;
  a26=7.2491903100000002e+02;
  a26=(a26*a12);
  a25=(a25+a26);
  a26=-1.9602528030000001e+03;
  a26=(a26*a09);
  a25=(a25+a26);
  a26=1.7332038110000001e+03;
  a26=(a26*a13);
  a25=(a25+a26);
  a26=(a24*a14);
  a27=(a25*a26);
  a22=(a22+a27);
  a27=7.1868526499999996e+02;
  a28=-1.7523918999999999e+01;
  a28=(a28*a12);
  a27=(a27+a28);
  a28=6.5252556180000001e+03;
  a28=(a28*a09);
  a27=(a27+a28);
  a28=-8.1779472100000003e+03;
  a28=(a28*a13);
  a27=(a27+a28);
  a28=(a26*a14);
  a29=(a27*a28);
  a22=(a22+a29);
  a29=3.2297709999999999e+00;
  a30=1.0991650999999999e+01;
  a30=(a30*a12);
  a29=(a29+a30);
  a30=-2.9369515000000000e+01;
  a30=(a30*a09);
  a29=(a29+a30);
  a30=2.6266324999999998e+01;
  a30=(a30*a13);
  a29=(a29+a30);
  a30=arg[0]? arg[0][15] : 0;
  a31=(a29*a30);
  a32=3.1419312999999999e+01;
  a33=-2.1712130999999999e+02;
  a33=(a33*a12);
  a32=(a32+a33);
  a33=3.9809161499999999e+02;
  a33=(a33*a09);
  a32=(a32+a33);
  a33=-2.0738472999999999e+02;
  a33=(a33*a13);
  a32=(a32+a33);
  a33=casadi_sq(a30);
  a34=(a33*a30);
  a35=(a32*a34);
  a31=(a31+a35);
  a35=-6.3957199500000002e+02;
  a36=1.9119816610000000e+03;
  a36=(a36*a12);
  a35=(a35+a36);
  a36=-2.9751745470000001e+03;
  a36=(a36*a09);
  a35=(a35+a36);
  a36=1.2345741399999999e+03;
  a36=(a36*a13);
  a35=(a35+a36);
  a36=(a34*a33);
  a37=(a35*a36);
  a31=(a31+a37);
  a37=2.4384083030000002e+03;
  a38=-3.1924757900000000e+03;
  a38=(a38*a12);
  a37=(a37+a38);
  a38=3.2756856130000001e+03;
  a38=(a38*a09);
  a37=(a37+a38);
  a38=-3.5469790100000000e+02;
  a38=(a38*a13);
  a37=(a37+a38);
  a33=(a36*a33);
  a38=(a37*a33);
  a31=(a31+a38);
  a22=(a22+a31);
  a22=(a05*a22);
  a31=(a22*a19);
  a20=(a20+a31);
  a21=(a21*a04);
  a31=(a15*a04);
  a23=(a23*a31);
  a21=(a21+a23);
  a23=(a31*a15);
  a25=(a25*a23);
  a21=(a21+a25);
  a25=(a23*a15);
  a27=(a27*a25);
  a21=(a21+a27);
  a27=arg[0]? arg[0][16] : 0;
  a29=(a29*a27);
  a38=casadi_sq(a27);
  a39=(a38*a27);
  a32=(a32*a39);
  a29=(a29+a32);
  a32=(a39*a38);
  a35=(a35*a32);
  a29=(a29+a35);
  a38=(a32*a38);
  a37=(a37*a38);
  a29=(a29+a37);
  a21=(a21+a29);
  a21=(a05*a21);
  a29=(a21*a16);
  a20=(a20+a29);
  a08=casadi_fmax(a08,a10);
  a29=(a06*a08);
  a20=(a20/a29);
  a37=cos(a17);
  a07=(a07*a37);
  a07=(a07/a08);
  a20=(a20-a07);
  if (res[0]!=0) res[0][1]=a20;
  a03=(a03*a16);
  a02=(a02*a19);
  a03=(a03-a02);
  a00=(a00*a03);
  a03=(a22*a16);
  a00=(a00+a03);
  a03=(a21*a19);
  a00=(a00-a03);
  a03=casadi_fabs(a37);
  a02=5.0000000000000003e-02;
  a03=casadi_fmax(a03,a02);
  a29=(a29*a03);
  a00=(a00/a29);
  if (res[0]!=0) res[0][2]=a00;
  a29=1.3000000000000000e-01;
  a05=(a29*a05);
  a03=5.7295800000000000e+01;
  a02=-2.9927300000000001e-01;
  a07=1.6744400000000001e-01;
  a07=(a07*a12);
  a02=(a02+a07);
  a07=-6.2697000000000003e-01;
  a07=(a07*a09);
  a02=(a02+a07);
  a07=3.9055699999999999e-01;
  a07=(a07*a13);
  a02=(a02+a07);
  a07=-4.7904600000000003e-01;
  a35=1.0339079000000000e+01;
  a35=(a35*a12);
  a07=(a07+a35);
  a35=-1.3302108000000000e+01;
  a35=(a35*a09);
  a07=(a07+a35);
  a35=2.2420140000000002e+00;
  a35=(a35*a13);
  a07=(a07+a35);
  a07=(a07*a14);
  a02=(a02+a07);
  a07=2.3625848999999999e+01;
  a35=-1.1080267600000001e+02;
  a35=(a35*a12);
  a07=(a07+a35);
  a35=1.4602420499999999e+02;
  a35=(a35*a09);
  a07=(a07+a35);
  a35=-4.9198385000000002e+01;
  a35=(a35*a13);
  a07=(a07+a35);
  a07=(a07*a14);
  a07=(a07*a14);
  a02=(a02+a07);
  a02=(a03*a02);
  a07=arg[0]? arg[0][3] : 0;
  a35=(a29*a07);
  a40=2.;
  a40=(a40*a08);
  a35=(a35/a40);
  a02=(a02*a35);
  a35=-1.8529970000000000e+00;
  a41=-4.3393290000000002e+00;
  a41=(a41*a12);
  a35=(a35+a41);
  a41=1.2372914000000000e+01;
  a41=(a41*a09);
  a35=(a35+a41);
  a41=-1.2716224000000000e+01;
  a41=(a41*a13);
  a35=(a35+a41);
  a41=arg[0]? arg[0][17] : 0;
  a35=(a35*a41);
  a02=(a02+a35);
  a02=(a05*a02);
  a35=3.5600000000000000e-02;
  a02=(a02/a35);
  if (res[0]!=0) res[0][3]=a02;
  a02=-9.2393249999999991e+00;
  a35=-5.9737910000000003e+00;
  a35=(a35*a12);
  a02=(a02+a35);
  a35=1.5860243000000001e+01;
  a35=(a35*a09);
  a02=(a02+a35);
  a35=-2.1574051000000001e+01;
  a35=(a35*a13);
  a02=(a02+a35);
  a01=(a02*a01);
  a35=-1.9155148000000001e+01;
  a42=2.1501682400000001e+02;
  a42=(a42*a12);
  a35=(a35+a42);
  a42=-5.1869263699999999e+02;
  a42=(a42*a09);
  a35=(a35+a42);
  a42=3.5413016800000003e+02;
  a42=(a42*a13);
  a35=(a35+a42);
  a24=(a35*a24);
  a01=(a01+a24);
  a24=2.5064975200000001e+02;
  a42=-1.6825658719999999e+03;
  a42=(a42*a12);
  a24=(a24+a42);
  a42=7.2841314869999997e+03;
  a42=(a42*a09);
  a24=(a24+a42);
  a42=-7.3169436640000004e+03;
  a42=(a42*a13);
  a24=(a24+a42);
  a26=(a24*a26);
  a01=(a01+a26);
  a26=2.9906044200000002e+02;
  a42=1.8524295729999999e+03;
  a42=(a42*a12);
  a26=(a26+a42);
  a42=-2.5896146472000000e+04;
  a42=(a42*a09);
  a26=(a26+a42);
  a42=3.1618867445000000e+04;
  a42=(a42*a13);
  a26=(a26+a42);
  a28=(a26*a28);
  a01=(a01+a28);
  a28=-1.1750583000000001e+01;
  a42=-3.9694744000000000e+01;
  a42=(a42*a12);
  a28=(a28+a42);
  a42=1.0621206599999999e+02;
  a42=(a42*a09);
  a28=(a28+a42);
  a42=-9.5130388999999994e+01;
  a42=(a42*a13);
  a28=(a28+a42);
  a42=(a28*a30);
  a43=-1.1208254100000001e+02;
  a44=7.7532038299999999e+02;
  a44=(a44*a12);
  a43=(a43+a44);
  a44=-1.4224302020000000e+03;
  a44=(a44*a09);
  a43=(a43+a44);
  a44=7.4173469899999998e+02;
  a44=(a44*a13);
  a43=(a43+a44);
  a34=(a43*a34);
  a42=(a42+a34);
  a34=2.2885326550000000e+03;
  a44=-6.7312745770000001e+03;
  a44=(a44*a12);
  a34=(a34+a44);
  a44=1.0450846055000000e+04;
  a44=(a44*a09);
  a34=(a34+a44);
  a44=-4.3223483800000004e+03;
  a44=(a44*a13);
  a34=(a34+a44);
  a36=(a34*a36);
  a42=(a42+a36);
  a36=-8.6958707730000006e+03;
  a44=1.0625281698000001e+04;
  a44=(a44*a12);
  a36=(a36+a44);
  a44=-1.0344266148000001e+04;
  a44=(a44*a09);
  a36=(a36+a44);
  a44=6.1871614199999999e+02;
  a44=(a44*a13);
  a36=(a36+a44);
  a33=(a36*a33);
  a42=(a42+a33);
  a01=(a01+a42);
  a42=-2.1924260000000002e+00;
  a33=-2.2064319999999999e+00;
  a33=(a33*a12);
  a42=(a42+a33);
  a33=7.5349209999999998e+00;
  a33=(a33*a09);
  a42=(a42+a33);
  a33=-8.8922419999999995e+00;
  a33=(a33*a13);
  a42=(a42+a33);
  a33=2.3478818000000000e+01;
  a44=5.7307955999999997e+01;
  a44=(a44*a12);
  a33=(a33+a44);
  a44=-1.0870987500000000e+02;
  a44=(a44*a09);
  a33=(a33+a44);
  a44=4.6111668000000002e+01;
  a44=(a44*a13);
  a33=(a33+a44);
  a44=(a33*a14);
  a44=(a42+a44);
  a45=-1.2221128999999999e+01;
  a46=-1.0148882810000000e+03;
  a46=(a46*a12);
  a45=(a45+a46);
  a46=1.7859279300000001e+03;
  a46=(a46*a09);
  a45=(a45+a46);
  a46=-7.6487703399999998e+02;
  a46=(a46*a13);
  a45=(a45+a46);
  a46=(a45*a14);
  a46=(a46*a14);
  a44=(a44+a46);
  a44=(a03*a44);
  a46=arg[0]? arg[0][4] : 0;
  a14=(a29*a46);
  a14=(a14/a40);
  a44=(a44*a14);
  a01=(a01+a44);
  a01=(a05*a01);
  a44=-3.6847723704865887e-03;
  a14=1.2739999999999998e+01;
  a14=(a14-a06);
  a06=1.6299999999999990e+00;
  a14=(a14/a06);
  a14=casadi_fmax(a14,a11);
  a14=casadi_fmin(a14,a10);
  a44=(a44*a14);
  a22=(a44*a22);
  a01=(a01+a22);
  a22=1.1580452295229522e+00;
  a10=-7.9145229522952221e-02;
  a10=(a10*a14);
  a22=(a22+a10);
  a01=(a01/a22);
  if (res[0]!=0) res[0][4]=a01;
  a28=(a28*a27);
  a43=(a43*a39);
  a28=(a28+a43);
  a34=(a34*a32);
  a28=(a28+a34);
  a36=(a36*a38);
  a28=(a28+a36);
  a02=(a02*a04);
  a35=(a35*a31);
  a02=(a02+a35);
  a24=(a24*a23);
  a02=(a02+a24);
  a26=(a26*a25);
  a02=(a02+a26);
  a28=(a28-a02);
  a33=(a33*a15);
  a42=(a42+a33);
  a45=(a45*a15);
  a45=(a45*a15);
  a42=(a42+a45);
  a03=(a03*a42);
  a42=arg[0]? arg[0][5] : 0;
  a29=(a29*a42);
  a29=(a29/a40);
  a03=(a03*a29);
  a28=(a28+a03);
  a05=(a05*a28);
  a44=(a44*a21);
  a05=(a05+a44);
  a44=1.1569718721872186e+00;
  a21=-7.9071872187218561e-02;
  a21=(a21*a14);
  a44=(a44+a21);
  a05=(a05/a44);
  if (res[0]!=0) res[0][5]=a05;
  a05=(a20*a19);
  a05=(a46-a05);
  a00=(a00*a37);
  a44=(a00*a16);
  a05=(a05-a44);
  if (res[0]!=0) res[0][6]=a05;
  a00=(a00*a19);
  a20=(a20*a16);
  a20=(a42+a20);
  a00=(a00-a20);
  if (res[0]!=0) res[0][7]=a00;
  a46=(a46*a16);
  a42=(a42*a19);
  a46=(a46+a42);
  a42=1.3999999999999999e+00;
  a17=casadi_fmin(a17,a42);
  a42=-1.3999999999999999e+00;
  a17=casadi_fmax(a17,a42);
  a17=tan(a17);
  a46=(a46*a17);
  a07=(a07+a46);
  if (res[0]!=0) res[0][8]=a07;
  a07=1.0000000000000000e-02;
  a18=(a08*a18);
  a07=(a07*a18);
  if (res[0]!=0) res[0][9]=a07;
  a07=1.0000000000000000e-03;
  a08=(a08*a37);
  a37=arg[0]? arg[0][2] : 0;
  a18=cos(a37);
  a18=(a08*a18);
  a18=(a07*a18);
  if (res[0]!=0) res[0][10]=a18;
  a37=sin(a37);
  a08=(a08*a37);
  a07=(a07*a08);
  if (res[0]!=0) res[0][11]=a07;
  a07=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][12]=a07;
  a07=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][13]=a07;
  a07=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][14]=a07;
  a07=arg[0]? arg[0][12] : 0;
  a07=(a07-a30);
  a30=1.4999999999999999e-02;
  a07=(a07/a30);
  if (res[0]!=0) res[0][15]=a07;
  a07=arg[0]? arg[0][13] : 0;
  a07=(a07-a27);
  a07=(a07/a30);
  if (res[0]!=0) res[0][16]=a07;
  a07=arg[0]? arg[0][14] : 0;
  a07=(a07-a41);
  a07=(a07/a30);
  if (res[0]!=0) res[0][17]=a07;
  return 0;
}

CASADI_SYMBOL_EXPORT int m130_rocket_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int m130_rocket_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int m130_rocket_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void m130_rocket_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int m130_rocket_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void m130_rocket_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void m130_rocket_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void m130_rocket_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int m130_rocket_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int m130_rocket_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real m130_rocket_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* m130_rocket_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* m130_rocket_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* m130_rocket_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* m130_rocket_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int m130_rocket_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int m130_rocket_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
