/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) m130_mhe_cost_y_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {17, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {9, 1, 1};
static const casadi_int casadi_s4[3] = {30, 1, 1};
static const casadi_int casadi_s5[82] = 
  {34, 30, 0, 2, 4, 6, 10, 14,
  18, 19, 20, 21, 22, 26, 30, 32,
  33, 34, 35, 36, 37, 38, 39, 40,
  41, 42, 43, 44, 45, 46, 47, 48,
  49, 20, 29, 21, 30, 22, 31, 17,
  23, 24, 26, 17, 23, 24, 26, 17,
  23, 24, 26, 26, 27, 28, 26, 17,
  18, 19, 32, 17, 18, 19, 33, 17,
  18, 0, 1, 2, 3, 4, 5, 6,
  7, 8, 9, 10, 11, 12, 13, 14,
  15, 16};
static const casadi_int casadi_s6[3] = {30, 0, 1};

/* m130_mhe_cost_y_fun_jac_ut_xt:(i0[17],i1[17],i2[0],i3[],i4[9])->(o0[30],o1[34x30,49nz],o2[30x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a000, a001, a002, a003, a004, a005, a006, a007, a008, a009, a010, a011;
  casadi_real a012, a013, a014, a015, a016, a017, a018, a019, a020, a021, a022, a023;
  casadi_real a024, a025, a026, a027, a028, a029, a030, a031, a032, a033, a034, a035;
  casadi_real a036, a037, a038, a039, a040, a041, a042, a043, a044, a045, a046, a047;
  casadi_real a048, a049, a050, a051, a052, a053, a054, a055, a056, a057, a058, a059;
  casadi_real a060, a061, a062, a063, a064, a065, a066, a067, a068, a069, a070, a071;
  casadi_real a072, a073, a074, a075, a076, a077, a078, a079, a080, a081, a082, a083;
  casadi_real a084, a085, a086, a087, a088, a089, a090, a091, a092, a093, a094, a095;
  casadi_real a096, a097, a098, a099, a100, a101, a102, a103, a104, a105, a106, a107;
  casadi_real a108, a109, a110, a111, a112, a113, a114, a115, a116, a117, a118, a119;
  casadi_real a120, a121, a122, a123, a124, a125, a126, a127, a128, a129, a130, a131;
  casadi_real a132, a133, a134;
  a000=arg[0]? arg[0][3] : 0;
  a001=arg[0]? arg[0][12] : 0;
  a000=(a000+a001);
  if (res[0]!=0) res[0][0]=a000;
  a000=arg[0]? arg[0][4] : 0;
  a001=arg[0]? arg[0][13] : 0;
  a000=(a000+a001);
  if (res[0]!=0) res[0][1]=a000;
  a000=arg[0]? arg[0][5] : 0;
  a001=arg[0]? arg[0][14] : 0;
  a000=(a000+a001);
  if (res[0]!=0) res[0][2]=a000;
  a000=arg[4]? arg[4][4] : 0;
  a001=1.3270000000000001e-02;
  a002=5.0000000000000000e-01;
  a003=1.2250000000000001e+00;
  a004=2.8814999999999998e+02;
  a005=6.4999999999999997e-03;
  a006=100.;
  a007=arg[0]? arg[0][9] : 0;
  a007=(a006*a007);
  a008=arg[4]? arg[4][8] : 0;
  a007=(a007+a008);
  a008=0.;
  a009=casadi_fmax(a007,a008);
  a009=(a005*a009);
  a009=(a004-a009);
  a010=2.1665000000000001e+02;
  a011=casadi_fmax(a009,a010);
  a004=(a011/a004);
  a012=4.2559323623598138e+00;
  a013=pow(a004,a012);
  a013=(a003*a013);
  a014=1.0000000000000000e-10;
  a015=casadi_fmax(a013,a014);
  a015=(a002*a015);
  a016=arg[0]? arg[0][0] : 0;
  a017=1.;
  a018=casadi_fmax(a016,a017);
  a019=(a015*a018);
  a020=(a019*a018);
  a020=(a001*a020);
  a021=6.4465099999999997e-01;
  a022=-6.6772809999999998e+00;
  a023=4.0187000000000000e+02;
  a011=(a023*a011);
  a011=sqrt(a011);
  a024=(a018/a011);
  a025=casadi_fmin(a024,a017);
  a026=1.0000000000000001e-01;
  a027=casadi_fmax(a025,a026);
  a028=casadi_fmin(a027,a017);
  a029=casadi_fmax(a028,a026);
  a030=(a022*a029);
  a021=(a021+a030);
  a030=5.6985242999999997e+01;
  a031=casadi_sq(a029);
  a032=(a030*a031);
  a021=(a021+a032);
  a032=-2.5248384700000000e+02;
  a033=(a031*a029);
  a034=(a032*a033);
  a021=(a021+a034);
  a034=6.1561736499999995e+02;
  a035=(a033*a029);
  a036=(a034*a035);
  a021=(a021+a036);
  a036=-8.3459076500000003e+02;
  a037=(a035*a029);
  a038=(a036*a037);
  a021=(a021+a038);
  a038=5.8734720100000004e+02;
  a039=(a037*a029);
  a040=(a038*a039);
  a021=(a021+a040);
  a040=-1.6562689000000000e+02;
  a041=(a039*a029);
  a041=(a040*a041);
  a021=(a021+a041);
  a041=5.6522999999999997e-02;
  a042=-9.9855799999999995e-01;
  a043=(a042*a029);
  a041=(a041+a043);
  a043=2.3926500000000002e+00;
  a044=(a043*a031);
  a041=(a041+a044);
  a044=-1.7378279999999999e+00;
  a045=(a044*a033);
  a041=(a041+a045);
  a045=arg[0]? arg[0][6] : 0;
  a046=casadi_sq(a045);
  a047=arg[0]? arg[0][7] : 0;
  a048=casadi_sq(a047);
  a049=(a046+a048);
  a050=(a041*a049);
  a021=(a021+a050);
  a050=-3.0486789999999999e+00;
  a051=5.4473490000000000e+00;
  a052=(a051*a029);
  a050=(a050+a052);
  a052=-9.6709250000000004e+00;
  a053=(a052*a031);
  a050=(a050+a053);
  a053=4.8268709999999997e+00;
  a054=(a053*a033);
  a050=(a050+a054);
  a054=casadi_sq(a049);
  a055=(a050*a054);
  a021=(a021+a055);
  a055=(a020*a021);
  a056=cos(a045);
  a057=(a055*a056);
  a058=cos(a047);
  a059=(a057*a058);
  a000=(a000-a059);
  a059=1.2622483000000001e+01;
  a060=1.1211672000000000e+01;
  a061=(a060*a029);
  a059=(a059+a061);
  a061=-2.8836583999999998e+01;
  a062=(a061*a031);
  a059=(a059+a062);
  a062=2.6861415999999998e+01;
  a063=(a062*a033);
  a059=(a059+a063);
  a063=(a059*a045);
  a064=1.4340211000000000e+01;
  a065=-1.0152808899999999e+02;
  a066=(a065*a029);
  a064=(a064+a066);
  a066=1.4161946200000000e+02;
  a067=(a066*a031);
  a064=(a064+a067);
  a067=-5.3997655999999999e+01;
  a068=(a067*a033);
  a064=(a064+a068);
  a068=(a046*a045);
  a069=(a064*a068);
  a063=(a063+a069);
  a069=-3.1844681800000001e+02;
  a070=7.2491903100000002e+02;
  a071=(a070*a029);
  a069=(a069+a071);
  a071=-1.9602528030000001e+03;
  a072=(a071*a031);
  a069=(a069+a072);
  a072=1.7332038110000001e+03;
  a073=(a072*a033);
  a069=(a069+a073);
  a073=(a068*a046);
  a074=(a069*a073);
  a063=(a063+a074);
  a074=7.1868526499999996e+02;
  a075=-1.7523918999999999e+01;
  a076=(a075*a029);
  a074=(a074+a076);
  a076=6.5252556180000001e+03;
  a077=(a076*a031);
  a074=(a074+a077);
  a077=-8.1779472100000003e+03;
  a078=(a077*a033);
  a074=(a074+a078);
  a078=(a073*a046);
  a079=(a074*a078);
  a063=(a063+a079);
  a079=3.2297709999999999e+00;
  a080=1.0991650999999999e+01;
  a081=(a080*a029);
  a079=(a079+a081);
  a081=-2.9369515000000000e+01;
  a082=(a081*a031);
  a079=(a079+a082);
  a082=2.6266324999999998e+01;
  a083=(a082*a033);
  a079=(a079+a083);
  a083=arg[4]? arg[4][0] : 0;
  a084=(a079*a083);
  a085=3.1419312999999999e+01;
  a086=-2.1712130999999999e+02;
  a087=(a086*a029);
  a085=(a085+a087);
  a087=3.9809161499999999e+02;
  a088=(a087*a031);
  a085=(a085+a088);
  a088=-2.0738472999999999e+02;
  a089=(a088*a033);
  a085=(a085+a089);
  a089=casadi_sq(a083);
  a090=(a089*a083);
  a091=(a085*a090);
  a084=(a084+a091);
  a091=-6.3957199500000002e+02;
  a092=1.9119816610000000e+03;
  a093=(a092*a029);
  a091=(a091+a093);
  a093=-2.9751745470000001e+03;
  a094=(a093*a031);
  a091=(a091+a094);
  a094=1.2345741399999999e+03;
  a095=(a094*a033);
  a091=(a091+a095);
  a095=(a090*a089);
  a096=(a091*a095);
  a084=(a084+a096);
  a096=2.4384083030000002e+03;
  a097=-3.1924757900000000e+03;
  a098=(a097*a029);
  a096=(a096+a098);
  a098=3.2756856130000001e+03;
  a099=(a098*a031);
  a096=(a096+a099);
  a099=-3.5469790100000000e+02;
  a100=(a099*a033);
  a096=(a096+a100);
  a089=(a095*a089);
  a100=(a096*a089);
  a084=(a084+a100);
  a063=(a063+a084);
  a084=(a020*a063);
  a100=sin(a045);
  a101=(a084*a100);
  a000=(a000+a101);
  a102=(a059*a047);
  a103=(a048*a047);
  a104=(a064*a103);
  a102=(a102+a104);
  a104=(a103*a048);
  a105=(a069*a104);
  a102=(a102+a105);
  a105=(a104*a048);
  a106=(a074*a105);
  a102=(a102+a106);
  a106=arg[4]? arg[4][1] : 0;
  a079=(a079*a106);
  a107=casadi_sq(a106);
  a108=(a107*a106);
  a085=(a085*a108);
  a079=(a079+a085);
  a085=(a108*a107);
  a091=(a091*a085);
  a079=(a079+a091);
  a107=(a085*a107);
  a096=(a096*a107);
  a079=(a079+a096);
  a102=(a102+a079);
  a079=(a020*a102);
  a096=sin(a047);
  a091=(a079*a096);
  a000=(a000+a091);
  a109=arg[4]? arg[4][3] : 0;
  a110=1.0000000000000000e-03;
  a109=casadi_fmax(a109,a110);
  a000=(a000/a109);
  if (res[0]!=0) res[0][3]=a000;
  a000=(a055*a096);
  a079=(a079*a058);
  a000=(a000+a079);
  a000=(a000/a109);
  a000=(-a000);
  if (res[0]!=0) res[0][4]=a000;
  a000=(a055*a100);
  a110=(a000*a058);
  a084=(a084*a056);
  a110=(a110+a084);
  a110=(a110/a109);
  a110=(-a110);
  if (res[0]!=0) res[0][5]=a110;
  if (res[0]!=0) res[0][6]=a007;
  a110=1000.;
  a111=arg[0]? arg[0][10] : 0;
  a111=(a110*a111);
  if (res[0]!=0) res[0][7]=a111;
  a111=arg[0]? arg[0][11] : 0;
  a111=(a110*a111);
  if (res[0]!=0) res[0][8]=a111;
  if (res[0]!=0) res[0][9]=a007;
  a111=arg[0]? arg[0][1] : 0;
  a112=cos(a111);
  a113=(a016*a112);
  a114=arg[0]? arg[0][2] : 0;
  a115=cos(a114);
  a116=(a113*a115);
  a117=arg[0]? arg[0][15] : 0;
  a117=(a116+a117);
  if (res[0]!=0) res[0][10]=a117;
  a114=sin(a114);
  a117=(a113*a114);
  a118=arg[0]? arg[0][16] : 0;
  a118=(a117+a118);
  if (res[0]!=0) res[0][11]=a118;
  a111=sin(a111);
  a118=(a016*a111);
  a119=(-a118);
  if (res[0]!=0) res[0][12]=a119;
  a119=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][13]=a119;
  a119=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][14]=a119;
  a119=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][15]=a119;
  a119=arg[1]? arg[1][3] : 0;
  if (res[0]!=0) res[0][16]=a119;
  a119=arg[1]? arg[1][4] : 0;
  if (res[0]!=0) res[0][17]=a119;
  a119=arg[1]? arg[1][5] : 0;
  if (res[0]!=0) res[0][18]=a119;
  a119=arg[1]? arg[1][6] : 0;
  if (res[0]!=0) res[0][19]=a119;
  a119=arg[1]? arg[1][7] : 0;
  if (res[0]!=0) res[0][20]=a119;
  a119=arg[1]? arg[1][8] : 0;
  if (res[0]!=0) res[0][21]=a119;
  a119=arg[1]? arg[1][9] : 0;
  if (res[0]!=0) res[0][22]=a119;
  a119=arg[1]? arg[1][10] : 0;
  if (res[0]!=0) res[0][23]=a119;
  a119=arg[1]? arg[1][11] : 0;
  if (res[0]!=0) res[0][24]=a119;
  a119=arg[1]? arg[1][12] : 0;
  if (res[0]!=0) res[0][25]=a119;
  a119=arg[1]? arg[1][13] : 0;
  if (res[0]!=0) res[0][26]=a119;
  a119=arg[1]? arg[1][14] : 0;
  if (res[0]!=0) res[0][27]=a119;
  a119=arg[1]? arg[1][15] : 0;
  if (res[0]!=0) res[0][28]=a119;
  a119=arg[1]? arg[1][16] : 0;
  if (res[0]!=0) res[0][29]=a119;
  if (res[1]!=0) res[1][0]=a017;
  if (res[1]!=0) res[1][1]=a017;
  if (res[1]!=0) res[1][2]=a017;
  if (res[1]!=0) res[1][3]=a017;
  if (res[1]!=0) res[1][4]=a017;
  if (res[1]!=0) res[1][5]=a017;
  a119=(a017<=a016);
  a016=(a016<=a017);
  a016=(a119+a016);
  a119=(a119/a016);
  a015=(a015*a119);
  a015=(a018*a015);
  a019=(a019*a119);
  a015=(a015+a019);
  a015=(a001*a015);
  a019=(a063*a015);
  a016=(a026<=a028);
  a028=(a028<=a026);
  a028=(a016+a028);
  a016=(a016/a028);
  a028=(a027<=a017);
  a027=(a017<=a027);
  a027=(a028+a027);
  a028=(a028/a027);
  a027=(a026<=a025);
  a025=(a025<=a026);
  a025=(a027+a025);
  a027=(a027/a025);
  a025=(a024<=a017);
  a026=(a017<=a024);
  a026=(a025+a026);
  a025=(a025/a026);
  a119=(a119/a011);
  a119=(a025*a119);
  a119=(a027*a119);
  a119=(a028*a119);
  a119=(a016*a119);
  a026=(a060*a119);
  a120=(a029+a029);
  a121=(a120*a119);
  a122=(a061*a121);
  a026=(a026+a122);
  a122=(a029*a121);
  a123=(a031*a119);
  a122=(a122+a123);
  a123=(a062*a122);
  a026=(a026+a123);
  a123=(a045*a026);
  a124=(a065*a119);
  a125=(a066*a121);
  a124=(a124+a125);
  a125=(a067*a122);
  a124=(a124+a125);
  a125=(a068*a124);
  a123=(a123+a125);
  a125=(a070*a119);
  a126=(a071*a121);
  a125=(a125+a126);
  a126=(a072*a122);
  a125=(a125+a126);
  a126=(a073*a125);
  a123=(a123+a126);
  a126=(a075*a119);
  a127=(a076*a121);
  a126=(a126+a127);
  a127=(a077*a122);
  a126=(a126+a127);
  a127=(a078*a126);
  a123=(a123+a127);
  a127=(a080*a119);
  a128=(a081*a121);
  a127=(a127+a128);
  a128=(a082*a122);
  a127=(a127+a128);
  a128=(a083*a127);
  a129=(a086*a119);
  a130=(a087*a121);
  a129=(a129+a130);
  a130=(a088*a122);
  a129=(a129+a130);
  a130=(a090*a129);
  a128=(a128+a130);
  a130=(a092*a119);
  a131=(a093*a121);
  a130=(a130+a131);
  a131=(a094*a122);
  a130=(a130+a131);
  a131=(a095*a130);
  a128=(a128+a131);
  a131=(a097*a119);
  a132=(a098*a121);
  a131=(a131+a132);
  a132=(a099*a122);
  a131=(a131+a132);
  a132=(a089*a131);
  a128=(a128+a132);
  a123=(a123+a128);
  a123=(a020*a123);
  a019=(a019+a123);
  a123=(a100*a019);
  a128=(a021*a015);
  a132=(a022*a119);
  a133=(a030*a121);
  a132=(a132+a133);
  a133=(a032*a122);
  a132=(a132+a133);
  a133=(a029*a122);
  a134=(a033*a119);
  a133=(a133+a134);
  a134=(a034*a133);
  a132=(a132+a134);
  a133=(a029*a133);
  a134=(a035*a119);
  a133=(a133+a134);
  a134=(a036*a133);
  a132=(a132+a134);
  a133=(a029*a133);
  a134=(a037*a119);
  a133=(a133+a134);
  a134=(a038*a133);
  a132=(a132+a134);
  a133=(a029*a133);
  a134=(a039*a119);
  a133=(a133+a134);
  a133=(a040*a133);
  a132=(a132+a133);
  a133=(a042*a119);
  a134=(a043*a121);
  a133=(a133+a134);
  a134=(a044*a122);
  a133=(a133+a134);
  a133=(a049*a133);
  a132=(a132+a133);
  a119=(a051*a119);
  a121=(a052*a121);
  a119=(a119+a121);
  a122=(a053*a122);
  a119=(a119+a122);
  a119=(a054*a119);
  a132=(a132+a119);
  a132=(a020*a132);
  a128=(a128+a132);
  a132=(a056*a128);
  a132=(a058*a132);
  a123=(a123-a132);
  a015=(a102*a015);
  a026=(a047*a026);
  a124=(a103*a124);
  a026=(a026+a124);
  a125=(a104*a125);
  a026=(a026+a125);
  a126=(a105*a126);
  a026=(a026+a126);
  a127=(a106*a127);
  a129=(a108*a129);
  a127=(a127+a129);
  a130=(a085*a130);
  a127=(a127+a130);
  a131=(a107*a131);
  a127=(a127+a131);
  a026=(a026+a127);
  a026=(a020*a026);
  a015=(a015+a026);
  a026=(a096*a015);
  a123=(a123+a026);
  a123=(a123/a109);
  if (res[1]!=0) res[1][6]=a123;
  a123=(a045+a045);
  a026=(a045*a123);
  a026=(a026+a046);
  a127=(a064*a026);
  a127=(a059+a127);
  a026=(a046*a026);
  a131=(a068*a123);
  a026=(a026+a131);
  a131=(a069*a026);
  a127=(a127+a131);
  a046=(a046*a026);
  a026=(a073*a123);
  a046=(a046+a026);
  a046=(a074*a046);
  a127=(a127+a046);
  a127=(a020*a127);
  a046=(a100*a127);
  a046=(a046+a084);
  a084=(a041*a123);
  a026=(a049+a049);
  a123=(a026*a123);
  a123=(a050*a123);
  a084=(a084+a123);
  a084=(a020*a084);
  a123=(a056*a084);
  a123=(a123-a000);
  a123=(a058*a123);
  a046=(a046-a123);
  a046=(a046/a109);
  if (res[1]!=0) res[1][7]=a046;
  a046=(a047+a047);
  a123=(a047*a046);
  a123=(a123+a048);
  a064=(a064*a123);
  a059=(a059+a064);
  a123=(a048*a123);
  a064=(a103*a046);
  a123=(a123+a064);
  a069=(a069*a123);
  a059=(a059+a069);
  a048=(a048*a123);
  a123=(a104*a046);
  a048=(a048+a123);
  a074=(a074*a048);
  a059=(a059+a074);
  a059=(a020*a059);
  a074=(a096*a059);
  a074=(a074+a079);
  a041=(a041*a046);
  a026=(a026*a046);
  a050=(a050*a026);
  a041=(a041+a050);
  a041=(a020*a041);
  a050=(a056*a041);
  a050=(a058*a050);
  a026=(a057*a096);
  a050=(a050-a026);
  a074=(a074-a050);
  a074=(a074/a109);
  if (res[1]!=0) res[1][8]=a074;
  a024=(a024/a011);
  a074=(a010<=a009);
  a009=(a009<=a010);
  a009=(a074+a009);
  a074=(a074/a009);
  a009=(a008<=a007);
  a007=(a007<=a008);
  a007=(a009+a007);
  a009=(a009/a007);
  a009=(a006*a009);
  a005=(a005*a009);
  a074=(a074*a005);
  a023=(a023*a074);
  a011=(a011+a011);
  a023=(a023/a011);
  a024=(a024*a023);
  a025=(a025*a024);
  a027=(a027*a025);
  a028=(a028*a027);
  a016=(a016*a028);
  a060=(a060*a016);
  a120=(a120*a016);
  a061=(a061*a120);
  a060=(a060+a061);
  a061=(a029*a120);
  a031=(a031*a016);
  a061=(a061+a031);
  a062=(a062*a061);
  a060=(a060+a062);
  a045=(a045*a060);
  a065=(a065*a016);
  a066=(a066*a120);
  a065=(a065+a066);
  a067=(a067*a061);
  a065=(a065+a067);
  a068=(a068*a065);
  a045=(a045+a068);
  a070=(a070*a016);
  a071=(a071*a120);
  a070=(a070+a071);
  a072=(a072*a061);
  a070=(a070+a072);
  a073=(a073*a070);
  a045=(a045+a073);
  a075=(a075*a016);
  a076=(a076*a120);
  a075=(a075+a076);
  a077=(a077*a061);
  a075=(a075+a077);
  a078=(a078*a075);
  a045=(a045+a078);
  a080=(a080*a016);
  a081=(a081*a120);
  a080=(a080+a081);
  a082=(a082*a061);
  a080=(a080+a082);
  a083=(a083*a080);
  a086=(a086*a016);
  a087=(a087*a120);
  a086=(a086+a087);
  a088=(a088*a061);
  a086=(a086+a088);
  a090=(a090*a086);
  a083=(a083+a090);
  a092=(a092*a016);
  a093=(a093*a120);
  a092=(a092+a093);
  a094=(a094*a061);
  a092=(a092+a094);
  a095=(a095*a092);
  a083=(a083+a095);
  a097=(a097*a016);
  a098=(a098*a120);
  a097=(a097+a098);
  a099=(a099*a061);
  a097=(a097+a099);
  a089=(a089*a097);
  a083=(a083+a089);
  a045=(a045+a083);
  a045=(a020*a045);
  a083=(a014<=a013);
  a013=(a013<=a014);
  a013=(a083+a013);
  a083=(a083/a013);
  a013=3.2559323623598138e+00;
  a004=pow(a004,a013);
  a012=(a012*a004);
  a004=3.4704147145583901e-03;
  a004=(a004*a074);
  a012=(a012*a004);
  a003=(a003*a012);
  a083=(a083*a003);
  a002=(a002*a083);
  a002=(a018*a002);
  a018=(a018*a002);
  a001=(a001*a018);
  a063=(a063*a001);
  a045=(a045-a063);
  a063=(a100*a045);
  a022=(a022*a016);
  a030=(a030*a120);
  a022=(a022+a030);
  a032=(a032*a061);
  a022=(a022+a032);
  a032=(a029*a061);
  a033=(a033*a016);
  a032=(a032+a033);
  a034=(a034*a032);
  a022=(a022+a034);
  a032=(a029*a032);
  a035=(a035*a016);
  a032=(a032+a035);
  a036=(a036*a032);
  a022=(a022+a036);
  a032=(a029*a032);
  a037=(a037*a016);
  a032=(a032+a037);
  a038=(a038*a032);
  a022=(a022+a038);
  a029=(a029*a032);
  a039=(a039*a016);
  a029=(a029+a039);
  a040=(a040*a029);
  a022=(a022+a040);
  a042=(a042*a016);
  a043=(a043*a120);
  a042=(a042+a043);
  a044=(a044*a061);
  a042=(a042+a044);
  a049=(a049*a042);
  a022=(a022+a049);
  a051=(a051*a016);
  a052=(a052*a120);
  a051=(a051+a052);
  a053=(a053*a061);
  a051=(a051+a053);
  a054=(a054*a051);
  a022=(a022+a054);
  a022=(a020*a022);
  a021=(a021*a001);
  a022=(a022-a021);
  a021=(a056*a022);
  a021=(a058*a021);
  a063=(a063-a021);
  a047=(a047*a060);
  a103=(a103*a065);
  a047=(a047+a103);
  a104=(a104*a070);
  a047=(a047+a104);
  a105=(a105*a075);
  a047=(a047+a105);
  a106=(a106*a080);
  a108=(a108*a086);
  a106=(a106+a108);
  a085=(a085*a092);
  a106=(a106+a085);
  a107=(a107*a097);
  a106=(a106+a107);
  a047=(a047+a106);
  a020=(a020*a047);
  a102=(a102*a001);
  a020=(a020-a102);
  a102=(a096*a020);
  a063=(a063+a102);
  a063=(a063/a109);
  if (res[1]!=0) res[1][9]=a063;
  a063=(a096*a128);
  a015=(a058*a015);
  a063=(a063+a015);
  a063=(a063/a109);
  a063=(-a063);
  if (res[1]!=0) res[1][10]=a063;
  a063=(a096*a084);
  a063=(a063/a109);
  a063=(-a063);
  if (res[1]!=0) res[1][11]=a063;
  a063=(a096*a041);
  a055=(a055*a058);
  a063=(a063+a055);
  a059=(a058*a059);
  a059=(a059-a091);
  a063=(a063+a059);
  a063=(a063/a109);
  a063=(-a063);
  if (res[1]!=0) res[1][12]=a063;
  a063=(a096*a022);
  a020=(a058*a020);
  a063=(a063+a020);
  a063=(a063/a109);
  a063=(-a063);
  if (res[1]!=0) res[1][13]=a063;
  a128=(a100*a128);
  a128=(a058*a128);
  a019=(a056*a019);
  a128=(a128+a019);
  a128=(a128/a109);
  a128=(-a128);
  if (res[1]!=0) res[1][14]=a128;
  a084=(a100*a084);
  a084=(a084+a057);
  a084=(a058*a084);
  a127=(a056*a127);
  a127=(a127-a101);
  a084=(a084+a127);
  a084=(a084/a109);
  a084=(-a084);
  if (res[1]!=0) res[1][15]=a084;
  a041=(a100*a041);
  a041=(a058*a041);
  a000=(a000*a096);
  a041=(a041-a000);
  a041=(a041/a109);
  a041=(-a041);
  if (res[1]!=0) res[1][16]=a041;
  a100=(a100*a022);
  a058=(a058*a100);
  a056=(a056*a045);
  a058=(a058+a056);
  a058=(a058/a109);
  a058=(-a058);
  if (res[1]!=0) res[1][17]=a058;
  if (res[1]!=0) res[1][18]=a006;
  if (res[1]!=0) res[1][19]=a110;
  if (res[1]!=0) res[1][20]=a110;
  if (res[1]!=0) res[1][21]=a006;
  a006=(a115*a112);
  if (res[1]!=0) res[1][22]=a006;
  a115=(a115*a118);
  a115=(-a115);
  if (res[1]!=0) res[1][23]=a115;
  a117=(-a117);
  if (res[1]!=0) res[1][24]=a117;
  if (res[1]!=0) res[1][25]=a017;
  a112=(a114*a112);
  if (res[1]!=0) res[1][26]=a112;
  a114=(a114*a118);
  a114=(-a114);
  if (res[1]!=0) res[1][27]=a114;
  if (res[1]!=0) res[1][28]=a116;
  if (res[1]!=0) res[1][29]=a017;
  a111=(-a111);
  if (res[1]!=0) res[1][30]=a111;
  a113=(-a113);
  if (res[1]!=0) res[1][31]=a113;
  if (res[1]!=0) res[1][32]=a017;
  if (res[1]!=0) res[1][33]=a017;
  if (res[1]!=0) res[1][34]=a017;
  if (res[1]!=0) res[1][35]=a017;
  if (res[1]!=0) res[1][36]=a017;
  if (res[1]!=0) res[1][37]=a017;
  if (res[1]!=0) res[1][38]=a017;
  if (res[1]!=0) res[1][39]=a017;
  if (res[1]!=0) res[1][40]=a017;
  if (res[1]!=0) res[1][41]=a017;
  if (res[1]!=0) res[1][42]=a017;
  if (res[1]!=0) res[1][43]=a017;
  if (res[1]!=0) res[1][44]=a017;
  if (res[1]!=0) res[1][45]=a017;
  if (res[1]!=0) res[1][46]=a017;
  if (res[1]!=0) res[1][47]=a017;
  if (res[1]!=0) res[1][48]=a017;
  return 0;
}

CASADI_SYMBOL_EXPORT int m130_mhe_cost_y_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int m130_mhe_cost_y_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int m130_mhe_cost_y_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void m130_mhe_cost_y_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int m130_mhe_cost_y_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void m130_mhe_cost_y_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void m130_mhe_cost_y_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void m130_mhe_cost_y_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int m130_mhe_cost_y_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int m130_mhe_cost_y_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real m130_mhe_cost_y_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* m130_mhe_cost_y_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* m130_mhe_cost_y_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* m130_mhe_cost_y_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* m130_mhe_cost_y_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int m130_mhe_cost_y_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int m130_mhe_cost_y_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
